"""Second batch of A1 supplemental vocabulary (~12 words/week) to reach ~800 words in 3 months."""

A1_BOOST_EXTRA: dict[int, list[tuple[str, str, str]]] = {
    1: [
        ("¿Cómo amaneció?", "How did you wake up?", "Как проснулся?"),
        ("hasta mañana", "see you tomorrow", "до завтра"),
        ("que le vaya bien", "have a good one (formal)", "всего хорошего"),
        ("un gusto", "a pleasure", "приятно"),
        ("presentarse", "to introduce oneself", "представляться"),
        ("el nombre", "name", "имя"),
        ("apellido", "last name", "фамилия"),
        ("¿De qué parte eres?", "Where are you from?", "Из какого ты места?"),
        ("extranjero", "foreigner (m)", "иностранец"),
        ("extranjera", "foreigner (f)", "иностранка"),
        ("la bienvenida", "the welcome", "приветствие"),
        ("el saludo", "greeting", "приветствие"),
    ],
    2: [
        ("veinticinco", "twenty-five", "двадцать пять"),
        ("media", "half", "половина"),
        ("entero", "whole", "целый"),
        ("par", "pair/even", "пара/чётный"),
        ("impar", "odd", "нечётный"),
        ("sumar", "to add", "складывать"),
        ("restar", "to subtract", "вычитать"),
        ("igual", "equal/same", "равный"),
        ("más o menos", "more or less", "более-менее"),
        ("aproximadamente", "approximately", "примерно"),
        ("el número", "number", "число"),
        ("la cantidad", "quantity", "количество"),
    ],
    3: [
        ("serio", "serious (m)", "серьёзный"),
        ("seria", "serious (f)", "серьёзная"),
        ("joven", "young", "молодой"),
        ("mayor", "older/elder", "старший"),
        ("listo", "ready/smart (m)", "готовый/умный"),
        ("lista", "ready/smart (f)", "готовая/умная"),
        ("importante", "important", "важный"),
        ("posible", "possible", "возможный"),
        ("imposible", "impossible", "невозможный"),
        ("normal", "normal", "нормальный"),
        ("raro", "weird", "странный"),
        ("diferente", "different", "другой"),
    ],
    4: [
        ("el esposo", "husband", "муж"),
        ("la esposa", "wife", "жена"),
        ("el novio", "boyfriend", "парень"),
        ("la novia", "girlfriend", "девушка"),
        ("el vecino", "neighbor (m)", "сосед"),
        ("la vecina", "neighbor (f)", "соседка"),
        ("el pariente", "relative", "родственник"),
        ("la gente", "people", "люди"),
        ("el hombre", "man", "мужчина"),
        ("la mujer", "woman", "женщина"),
        ("el niño", "boy/child", "мальчик/ребёнок"),
        ("la niña", "girl", "девочка"),
    ],
    5: [
        ("la bebida", "drink", "напиток"),
        ("el jugo", "juice", "сок"),
        ("la cerveza", "beer", "пиво"),
        ("el vino", "wine", "вино"),
        ("la ensalada", "salad", "салат"),
        ("la sopa", "soup", "суп"),
        ("el postre", "dessert", "десерт"),
        ("el helado", "ice cream", "мороженое"),
        ("la receta", "recipe", "рецепт"),
        ("cocinar", "to cook", "готовить"),
        ("probar", "to try/taste", "пробовать"),
        ("pedir", "to order/ask for", "заказывать"),
    ],
    6: [
        ("usar", "to use", "использовать"),
        ("ayudar", "to help", "помогать"),
        ("limpiar", "to clean", "убирать"),
        ("cocinar", "to cook", "готовить"),
        ("preparar", "to prepare", "готовить"),
        ("terminar", "to finish", "заканчивать"),
        ("empezar", "to start", "начинать"),
        ("esperar", "to wait/hope", "ждать/надеяться"),
        ("ganar", "to win/earn", "выигрывать/зарабатывать"),
        ("perder", "to lose", "терять"),
        ("viajar", "to travel", "путешествовать"),
        ("visitar", "to visit", "посещать"),
    ],
    7: [
        ("vender", "to sell", "продавать"),
        ("meter", "to put in", "класть внутрь"),
        ("sacar", "to take out", "доставать"),
        ("traer", "to bring", "приносить"),
        ("llevar", "to carry/take", "нести/отвозить"),
        ("dejar", "to leave/let", "оставлять/позволять"),
        ("seguir", "to follow/continue", "следовать/продолжать"),
        ("salir", "to go out/leave", "выходить"),
        ("entrar", "to enter", "входить"),
        ("volver", "to return", "возвращаться"),
        ("olvidar", "to forget", "забывать"),
        ("recordar", "to remember", "помнить"),
    ],
    8: [
        ("la fecha", "date", "дата"),
        ("temprano", "early", "рано"),
        ("tarde", "late", "поздно"),
        ("pronto", "soon", "скоро"),
        ("luego", "then/later", "потом"),
        ("ahora", "now", "сейчас"),
        ("siempre", "always", "всегда"),
        ("nunca", "never", "никогда"),
        ("a veces", "sometimes", "иногда"),
        ("cada día", "every day", "каждый день"),
        ("la cita", "appointment", "встреча/запись"),
        ("puntual", "punctual", "пунктуальный"),
    ],
    9: [
        ("lento", "slow", "медленный"),
        ("rápido", "fast", "быстрый"),
        ("fuerte", "strong/loud", "сильный/громкий"),
        ("débil", "weak", "слабый"),
        ("lleno", "full", "полный"),
        ("vacío", "empty", "пустой"),
        ("correcto", "correct", "правильный"),
        ("incorrecto", "incorrect", "неправильный"),
        ("perfecto", "perfect", "идеальный"),
        ("horrible", "horrible", "ужасный"),
        ("hermoso", "beautiful", "красивый"),
        ("feo", "ugly", "уродливый"),
    ],
    10: [
        ("necesitar", "to need", "нуждаться"),
        ("preferir", "to prefer", "предпочитать"),
        ("parecer", "to seem", "казаться"),
        ("olvidar", "to forget", "забывать"),
        ("recordar", "to remember", "помнить"),
        ("creer", "to believe", "верить"),
        ("pensar", "to think", "думать"),
        ("sentir", "to feel", "чувствовать"),
        ("saber", "to know (fact)", "знать"),
        ("conocer", "to know (person)", "знать (человека)"),
        ("la razón", "reason", "причина"),
        ("la verdad", "truth", "правда"),
    ],
    11: [
        ("venir", "to come", "приходить"),
        ("llegar", "to arrive", "прибывать"),
        ("salir", "to leave", "уходить"),
        ("pasar", "to pass/happen", "проходить/случаться"),
        ("quedar", "to stay/meet", "оставаться/встречаться"),
        ("encontrar", "to find/meet", "находить/встречать"),
        ("cambiar", "to change", "менять"),
        ("empezar", "to begin", "начинать"),
        ("acabar", "to finish", "заканчивать"),
        ("seguir", "to continue", "продолжать"),
        ("el camino", "path/way", "путь"),
        ("la dirección", "direction/address", "направление/адрес"),
    ],
    12: [
        ("dormí", "I slept", "я спал"),
        ("trabajé", "I worked", "я работал"),
        ("estudié", "I studied", "я учился"),
        ("salí", "I went out", "я вышел"),
        ("llegué", "I arrived", "я прибыл"),
        ("compré", "I bought", "я купил"),
        ("vendí", "I sold", "я продал"),
        ("aprendí", "I learned", "я выучил"),
        ("perdí", "I lost", "я потерял"),
        ("gané", "I won", "я выиграл"),
        ("el recuerdo", "memory", "воспоминание"),
        ("la experiencia", "experience", "опыт"),
    ],
    13: [
        ("espero", "I hope", "я надеюсь"),
        ("creo que", "I think that", "я думаю что"),
        ("me gustaría", "I would like", "мне бы хотелось"),
        ("voy a empezar", "I'm going to start", "я начну"),
        ("el progreso", "progress", "прогресс"),
        ("el esfuerzo", "effort", "усилие"),
        ("la confianza", "confidence", "уверенность"),
        ("el miedo", "fear", "страх"),
        ("el éxito", "success", "успех"),
        ("el error", "mistake", "ошибка"),
        ("seguir adelante", "to keep going", "продолжать"),
        ("nunca es tarde", "it's never too late", "никогда не поздно"),
    ],
}
