"""Extra A1 vocabulary per week — pushes the 3-month track toward ~800 words + grammar chunks."""

# (es, en, ru) tuples merged into each authored A1 week at build time.
A1_BOOST: dict[int, list[tuple[str, str, str]]] = {
    1: [
        ("hasta luego", "see you later", "до скорого"),
        ("nos vemos", "see you", "увидимся"),
        ("¿Qué tal?", "how's it going?", "как дела?"),
        ("bienvenido", "welcome", "добро пожаловать"),
        ("bienvenida", "welcome (f)", "добро пожаловать (ж)"),
        ("señor", "Mr./sir", "господин"),
        ("señora", "Mrs./ma'am", "госпожа"),
        ("amigo", "friend (m)", "друг"),
        ("amiga", "friend (f)", "подруга"),
        ("encantado", "pleased to meet you (m)", "рад познакомиться"),
        ("encantada", "pleased to meet you (f)", "рада познакомиться"),
        ("igualmente", "likewise", "взаимно"),
        ("disculpe", "excuse me (formal)", "извините"),
        ("permiso", "excuse me / permission", "разрешите"),
        ("con permiso", "excuse me (passing)", "извините, пройду"),
        ("un momento", "one moment", "минуточку"),
        ("espere", "wait (formal)", "подождите"),
        ("cuídate", "take care", "береги себя"),
        ("saludos", "greetings/regards", "приветы"),
        ("claro", "of course", "конечно"),
        ("buena suerte", "good luck", "удачи"),
        ("oye", "hey", "слушай"),
        ("mira", "look", "смотри"),
        ("mande", "pardon? (Mexican)", "что? (мекс.)"),
        ("órale", "wow / come on (Mexican)", "ну давай (мекс.)"),
        ("ánimo", "cheer up / go for it", "давай, ты можешь"),
        ("chao", "bye (casual)", "пока"),
        ("¿Cuánto tiempo!", "long time no see!", "сколько времени!"),
        ("presentar", "to introduce", "представлять"),
        ("conocer", "to meet/know", "знакомиться/знать"),
        ("formal", "formal", "формальный"),
        ("informal", "informal", "неформальный"),
        ("usted", "you (formal)", "Вы (форм.)"),
        ("¿Cómo está usted?", "How are you? (formal)", "Как Вы?"),
        ("Me llamo Juan.", "My name is Juan.", "Меня зовут Хуан."),
        ("¿Cómo se llama?", "What's your name? (formal)", "Как Вас зовут?"),
        ("Le presento a...", "Let me introduce...", "Позвольте представить..."),
        ("Es un placer", "It's a pleasure", "Это удовольствие"),
    ],
    2: [
        ("dieciséis", "sixteen", "шестнадцать"),
        ("diecisiete", "seventeen", "семнадцать"),
        ("dieciocho", "eighteen", "восемнадцать"),
        ("diecinueve", "nineteen", "девятнадцать"),
        ("veintiuno", "twenty-one", "двадцать один"),
        ("veintidós", "twenty-two", "двадцать два"),
        ("cuarenta", "forty", "сорок"),
        ("cincuenta", "fifty", "пятьдесят"),
        ("sesenta", "sixty", "шестьдесят"),
        ("setenta", "seventy", "семьдесят"),
        ("ochenta", "eighty", "восемьдесят"),
        ("noventa", "ninety", "девяносто"),
        ("mil", "one thousand", "тысяча"),
        ("primero", "first", "первый"),
        ("segundo", "second", "второй"),
        ("tercero", "third", "третий"),
        ("el perro", "dog", "собака"),
        ("el gato", "cat", "кот"),
        ("la mesa", "table", "стол"),
        ("la silla", "chair", "стул"),
        ("el agua", "water", "вода"),
        ("la comida", "food", "еда"),
        ("el taco", "taco", "тако"),
        ("la playa", "beach", "пляж"),
        ("el coche", "car", "машина"),
        ("la calle", "street", "улица"),
        ("el parque", "park", "парк"),
        ("la escuela", "school", "школа"),
        ("el teléfono", "phone", "телефон"),
        ("la puerta", "door", "дверь"),
        ("un", "a/an (m)", "неопр. арт. м.р."),
        ("una", "a/an (f)", "неопр. арт. ж.р."),
        ("unos", "some (m pl)", "несколько (м)"),
        ("unas", "some (f pl)", "несколько (ж)"),
        ("¿Cuántos?", "How many? (m)", "Сколько? (м)"),
        ("¿Cuántas?", "How many? (f)", "Сколько? (ж)"),
        ("Tengo veinticinco años.", "I'm 25 years old.", "Мне 25 лет."),
        ("Es la número uno.", "It's number one.", "Это номер один."),
    ],
    3: [
        ("ser", "to be (permanent)", "быть (ser)"),
        ("estar", "to be (temporary)", "быть (estar)"),
        ("sois", "you are (Spain pl)", "вы есть (Исп.)"),
        ("estáis", "you are (Spain pl, estar)", "вы находитесь (Исп.)"),
        ("bueno", "good (m)", "хороший"),
        ("buena", "good (f)", "хорошая"),
        ("malo", "bad (m)", "плохой"),
        ("mala", "bad (f)", "плохая"),
        ("alto", "tall (m)", "высокий"),
        ("alta", "tall (f)", "высокая"),
        ("bajo", "short (m)", "низкий"),
        ("baja", "short (f)", "низкая"),
        ("feliz", "happy", "счастливый"),
        ("triste", "sad", "грустный"),
        ("enfermo", "sick (m)", "больной"),
        ("enferma", "sick (f)", "больная"),
        ("ocupado", "busy (m)", "занятой"),
        ("ocupada", "busy (f)", "занятая"),
        ("abierto", "open (m)", "открытый"),
        ("cerrado", "closed (m)", "закрытый"),
        ("de", "from/of", "из/от"),
        ("en", "in/on", "в/на"),
        ("México", "Mexico", "Мексика"),
        ("español", "Spanish", "испанский"),
        ("mexicano", "Mexican (m)", "мексиканец"),
        ("mexicana", "Mexican (f)", "мексиканка"),
        ("profesor", "teacher (m)", "учитель"),
        ("profesora", "teacher (f)", "учительница"),
        ("estudiante", "student", "студент"),
        ("amable", "kind", "добрый"),
        ("inteligente", "intelligent", "умный"),
        ("¿De dónde eres?", "Where are you from?", "Откуда ты?"),
        ("Soy de...", "I'm from...", "Я из..."),
        ("Estoy en la casa.", "I'm at home.", "Я дома."),
        ("Está cerrado.", "It's closed.", "Закрыто."),
        ("Son las tres.", "It's three o'clock.", "Три часа."),
        ("Es importante.", "It's important.", "Это важно."),
        ("Estoy contento.", "I'm happy.", "Я доволен."),
        ("¿Cómo es?", "What is it like?", "Какой он/она?"),
        ("¿Cómo estás hoy?", "How are you today?", "Как ты сегодня?"),
    ],
    4: [
        ("la familia", "family", "семья"),
        ("el padre", "father", "отец"),
        ("la madre", "mother", "мать"),
        ("el hijo", "son", "сын"),
        ("la hija", "daughter", "дочь"),
        ("el hermano", "brother", "брат"),
        ("la hermana", "sister", "сестра"),
        ("el abuelo", "grandfather", "дедушка"),
        ("la abuela", "grandmother", "бабушка"),
        ("el tío", "uncle", "дядя"),
        ("la tía", "aunt", "тётя"),
        ("el primo", "cousin (m)", "двоюродный брат"),
        ("la prima", "cousin (f)", "двоюродная сестра"),
        ("el esposo", "husband", "муж"),
        ("la esposa", "wife", "жена"),
        ("mi", "my", "мой/моя"),
        ("tu", "your", "твой/твоя"),
        ("su", "his/her/their", "его/её/их"),
        ("nuestro", "our (m)", "наш"),
        ("nuestra", "our (f)", "наша"),
        ("¿Cuántos hermanos tienes?", "How many siblings?", "Сколько у тебя братьев/сестёр?"),
        ("Mi familia es grande.", "My family is big.", "У меня большая семья."),
        ("Es mi madre.", "She's my mother.", "Это моя мать."),
        ("Tengo dos hijos.", "I have two children.", "У меня двое детей."),
        ("¿Tienes hijos?", "Do you have children?", "У тебя есть дети?"),
        ("Vivo con mi familia.", "I live with my family.", "Я живу с семьёй."),
        ("el nieto", "grandson", "внук"),
        ("la nieta", "granddaughter", "внучка"),
        ("el bebé", "baby", "малыш"),
        ("los padres", "parents", "родители"),
        ("los abuelos", "grandparents", "бабушка и дедушка"),
        ("mayor", "older", "старший"),
        ("menor", "younger", "младший"),
        ("solo", "only/alone", "единственный/один"),
        ("casado", "married (m)", "женатый"),
        ("casada", "married (f)", "замужняя"),
        ("soltero", "single (m)", "холост"),
        ("soltera", "single (f)", "не замужем"),
        ("¿Estás casado?", "Are you married?", "Ты женат?"),
    ],
    5: [
        ("el desayuno", "breakfast", "завтрак"),
        ("el almuerzo", "lunch", "обед"),
        ("la cena", "dinner", "ужин"),
        ("el pan", "bread", "хлеб"),
        ("el arroz", "rice", "рис"),
        ("el pollo", "chicken", "курица"),
        ("la carne", "meat", "мясо"),
        ("el pescado", "fish", "рыба"),
        ("la fruta", "fruit", "фрукты"),
        ("la verdura", "vegetable", "овощи"),
        ("el huevo", "egg", "яйцо"),
        ("la leche", "milk", "молоко"),
        ("el queso", "cheese", "сыр"),
        ("el azúcar", "sugar", "сахар"),
        ("la sal", "salt", "соль"),
        ("picante", "spicy", "острый"),
        ("dulce", "sweet", "сладкий"),
        ("rico", "tasty", "вкусный"),
        ("Me gusta el café.", "I like coffee.", "Мне нравится кофе."),
        ("No me gusta.", "I don't like it.", "Мне не нравится."),
        ("¿Te gusta?", "Do you like it?", "Тебе нравится?"),
        ("Me encanta.", "I love it.", "Обожаю."),
        ("Tengo hambre.", "I'm hungry.", "Я голоден."),
        ("Tengo sed.", "I'm thirsty.", "Я хочу пить."),
        ("Quiero agua.", "I want water.", "Я хочу воды."),
        ("La cuenta, por favor.", "The bill, please.", "Счёт, пожалуйста."),
        ("¿Qué quieres comer?", "What do you want to eat?", "Что хочешь есть?"),
        ("Está delicioso.", "It's delicious.", "Очень вкусно."),
        ("un poco", "a little", "немного"),
        ("mucho", "a lot", "много"),
        ("más", "more", "ещё/больше"),
        ("menos", "less", "меньше"),
        ("sin", "without", "без"),
        ("con", "with", "с"),
        ("para", "for", "для"),
        ("el restaurante", "restaurant", "ресторан"),
        ("la cocina", "kitchen", "кухня"),
        ("el plato", "dish/plate", "блюдо/тарелка"),
    ],
    6: [
        ("hablar", "to speak", "говорить"),
        ("trabajar", "to work", "работать"),
        ("estudiar", "to study", "учиться"),
        ("caminar", "to walk", "гулять"),
        ("bailar", "to dance", "танцевать"),
        ("cantar", "to sing", "петь"),
        ("comprar", "to buy", "покупать"),
        ("vender", "to sell", "продавать"),
        ("llamar", "to call", "звонить"),
        ("escuchar", "to listen", "слушать"),
        ("mirar", "to look at", "смотреть"),
        ("necesitar", "to need", "нуждаться"),
        ("buscar", "to look for", "искать"),
        ("encontrar", "to find", "находить"),
        ("preguntar", "to ask", "спрашивать"),
        ("contestar", "to answer", "отвечать"),
        ("Yo hablo español.", "I speak Spanish.", "Я говорю по-испански."),
        ("¿Hablas inglés?", "Do you speak English?", "Ты говоришь по-английски?"),
        ("Trabajo en casa.", "I work at home.", "Я работаю дома."),
        ("Estudio todos los días.", "I study every day.", "Я учусь каждый день."),
        ("¿Qué haces?", "What are you doing?", "Что ты делаешь?"),
        ("Hago ejercicio.", "I exercise.", "Я занимаюсь спортом."),
        ("todos los días", "every day", "каждый день"),
        ("a veces", "sometimes", "иногда"),
        ("nunca", "never", "никогда"),
        ("siempre", "always", "всегда"),
        ("ahora", "now", "сейчас"),
        ("después", "after/later", "потом"),
        ("antes", "before", "раньше"),
        ("temprano", "early", "рано"),
        ("tarde", "late", "поздно"),
        ("mucho", "a lot", "много"),
        ("poco", "little", "мало"),
        ("bien", "well", "хорошо"),
        ("mal", "badly", "плохо"),
        ("también", "also", "тоже"),
        ("tampoco", "neither", "тоже не"),
        ("¿A qué hora?", "At what time?", "Во сколько?"),
    ],
    7: [
        ("comer", "to eat", "есть"),
        ("beber", "to drink", "пить"),
        ("leer", "to read", "читать"),
        ("escribir", "to write", "писать"),
        ("vivir", "to live", "жить"),
        ("abrir", "to open", "открывать"),
        ("recibir", "to receive", "получать"),
        ("decidir", "to decide", "решать"),
        ("comprender", "to understand", "понимать"),
        ("aprender", "to learn", "учить/учиться"),
        ("correr", "to run", "бегать"),
        ("partir", "to leave/depart", "уезжать"),
        ("subir", "to go up", "подниматься"),
        ("escribo", "I write", "я пишу"),
        ("leo", "I read", "я читаю"),
        ("como", "I eat", "я ем"),
        ("bebo", "I drink", "я пью"),
        ("vivo", "I live", "я живу"),
        ("¿Comes carne?", "Do you eat meat?", "Ты ешь мясо?"),
        ("No comprendo.", "I don't understand.", "Я не понимаю."),
        ("Entiendo un poco.", "I understand a little.", "Я понимаю немного."),
        ("¿Puedes repetir?", "Can you repeat?", "Можешь повторить?"),
        ("Más despacio, por favor.", "Slower, please.", "Помедленнее, пожалуйста."),
        ("el verbo", "verb", "глагол"),
        ("la conjugación", "conjugation", "спряжение"),
        ("la forma", "form", "форма"),
        ("regular", "regular", "правильный"),
        ("irregular", "irregular", "неправильный"),
        ("terminación", "ending", "окончание"),
        ("-er", "-er ending", "окончание -er"),
        ("-ir", "-ir ending", "окончание -ir"),
        ("nosotros comemos", "we eat", "мы едим"),
        ("ellos viven", "they live", "они живут"),
        ("¿Dónde vives?", "Where do you live?", "Где ты живёшь?"),
        ("Vivo en México.", "I live in Mexico.", "Я живу в Мексике."),
        ("Leo un libro.", "I read a book.", "Я читаю книгу."),
        ("Escribo un mensaje.", "I write a message.", "Я пишу сообщение."),
        ("Aprendo español.", "I'm learning Spanish.", "Я учу испанский."),
    ],
    8: [
        ("lunes", "Monday", "понедельник"),
        ("martes", "Tuesday", "вторник"),
        ("miércoles", "Wednesday", "среда"),
        ("jueves", "Thursday", "четверг"),
        ("viernes", "Friday", "пятница"),
        ("sábado", "Saturday", "суббота"),
        ("domingo", "Sunday", "воскресенье"),
        ("enero", "January", "январь"),
        ("febrero", "February", "февраль"),
        ("marzo", "March", "март"),
        ("abril", "April", "апрель"),
        ("mayo", "May", "май"),
        ("junio", "June", "июнь"),
        ("julio", "July", "июль"),
        ("agosto", "August", "август"),
        ("septiembre", "September", "сентябрь"),
        ("octubre", "October", "октябрь"),
        ("noviembre", "November", "ноябрь"),
        ("diciembre", "December", "декабрь"),
        ("la hora", "hour/time", "час/время"),
        ("el minuto", "minute", "минута"),
        ("la semana", "week", "неделя"),
        ("el mes", "month", "месяц"),
        ("el año", "year", "год"),
        ("hoy", "today", "сегодня"),
        ("mañana", "tomorrow", "завтра"),
        ("ayer", "yesterday", "вчера"),
        ("¿Qué día es hoy?", "What day is today?", "Какой сегодня день?"),
        ("¿Qué hora es?", "What time is it?", "Который час?"),
        ("Son las ocho.", "It's eight o'clock.", "Восемь часов."),
        ("Es mediodía.", "It's noon.", "Полдень."),
        ("Es medianoche.", "It's midnight.", "Полночь."),
        ("de la mañana", "in the morning", "утром"),
        ("de la tarde", "in the afternoon", "днём"),
        ("de la noche", "at night", "ночью"),
        ("el fin de semana", "weekend", "выходные"),
        ("entre semana", "on weekdays", "на неделе"),
        ("¿Cuándo?", "When?", "Когда?"),
    ],
    9: [
        ("grande", "big", "большой"),
        ("pequeño", "small (m)", "маленький"),
        ("pequeña", "small (f)", "маленькая"),
        ("nuevo", "new (m)", "новый"),
        ("nueva", "new (f)", "новая"),
        ("viejo", "old (m)", "старый"),
        ("vieja", "old (f)", "старая"),
        ("bonito", "pretty (m)", "красивый"),
        ("bonita", "pretty (f)", "красивая"),
        ("feo", "ugly (m)", "уродливый"),
        ("largo", "long", "длинный"),
        ("corto", "short", "короткий"),
        ("caro", "expensive", "дорогой"),
        ("barato", "cheap", "дешёвый"),
        ("fácil", "easy", "лёгкий"),
        ("difícil", "difficult", "трудный"),
        ("interesante", "interesting", "интересный"),
        ("aburrido", "boring", "скучный"),
        ("limpio", "clean", "чистый"),
        ("sucio", "dirty", "грязный"),
        ("muy", "very", "очень"),
        ("bastante", "quite", "довольно"),
        ("demasiado", "too much", "слишком"),
        ("tan", "so", "так"),
        ("más ... que", "more ... than", "больше ... чем"),
        ("menos ... que", "less ... than", "меньше ... чем"),
        ("tan ... como", "as ... as", "такой же ... как"),
        ("Es muy grande.", "It's very big.", "Очень большой."),
        ("Es más caro que...", "It's more expensive than...", "Дороже чем..."),
        ("¿Cómo es tu casa?", "What's your house like?", "Какой у тебя дом?"),
        ("Mi coche es nuevo.", "My car is new.", "Моя машина новая."),
        ("Esta camisa es bonita.", "This shirt is pretty.", "Эта рубашка красивая."),
        ("el color", "color", "цвет"),
        ("rojo", "red", "красный"),
        ("azul", "blue", "синий"),
        ("verde", "green", "зелёный"),
        ("negro", "black", "чёрный"),
        ("blanco", "white", "белый"),
        ("amarillo", "yellow", "жёлтый"),
        ("¿De qué color?", "What color?", "Какого цвета?"),
    ],
    10: [
        ("tener", "to have", "иметь"),
        ("tengo", "I have", "у меня есть"),
        ("tienes", "you have", "у тебя есть"),
        ("tiene", "he/she has", "у него/неё есть"),
        ("tenemos", "we have", "у нас есть"),
        ("tienen", "they have", "у них есть"),
        ("tener frío", "to be cold", "замёрзнуть"),
        ("tener calor", "to be hot", "жарко"),
        ("tener miedo", "to be afraid", "бояться"),
        ("tener prisa", "to be in a hurry", "торопиться"),
        ("tener razón", "to be right", "быть правым"),
        ("tener sueño", "to be sleepy", "хочется спать"),
        ("tener suerte", "to be lucky", "везёт"),
        ("¿Cuántos años tienes?", "How old are you?", "Сколько тебе лет?"),
        ("Tengo veinte años.", "I'm twenty.", "Мне двадцать."),
        ("¿Qué tienes?", "What's wrong?", "Что с тобой?"),
        ("No tengo tiempo.", "I don't have time.", "У меня нет времени."),
        ("Tengo una idea.", "I have an idea.", "У меня есть идея."),
        ("¿Tienes hermanos?", "Do you have siblings?", "Есть братья/сёстры?"),
        ("hay", "there is/are", "есть/имеется"),
        ("¿Hay...?", "Is there...?", "Есть ли...?"),
        ("No hay.", "There isn't.", "Нет."),
        ("algo", "something", "что-то"),
        ("nada", "nothing", "ничего"),
        ("alguien", "someone", "кто-то"),
        ("nadie", "no one", "никто"),
        ("todo", "everything/all", "всё"),
        ("cada", "each/every", "каждый"),
        ("otro", "other/another", "другой"),
        ("mismo", "same", "тот же"),
        ("problema", "problem", "проблема"),
        ("solución", "solution", "решение"),
        ("dinero", "money", "деньги"),
        ("tiempo", "time", "время"),
        ("trabajo", "work/job", "работа"),
        ("casa", "home", "дом"),
        ("cosa", "thing", "вещь"),
        ("persona", "person", "человек"),
    ],
    11: [
        ("ir", "to go", "идти/ехать"),
        ("voy", "I go", "я иду"),
        ("vas", "you go", "ты идешь"),
        ("va", "he/she goes", "он/она идёт"),
        ("vamos", "we go / let's go", "мы идём / пойдём"),
        ("van", "they go", "они идут"),
        ("ir a + infinitive", "going to (near future)", "собираться (будущ.)"),
        ("Voy a estudiar.", "I'm going to study.", "Я собираюсь учиться."),
        ("¿Vamos?", "Shall we go?", "Пойдём?"),
        ("¿Adónde vas?", "Where are you going?", "Куда ты идешь?"),
        ("Voy al mercado.", "I'm going to the market.", "Я иду на рынок."),
        ("estoy + -ando/-iendo", "I am ...-ing (now)", "я сейчас ..."),
        ("Estoy comiendo.", "I'm eating.", "Я ем (сейчас)."),
        ("Está lloviendo.", "It's raining.", "Идёт день."),
        ("¿Qué estás haciendo?", "What are you doing?", "Что ты делаешь?"),
        ("ahora mismo", "right now", "прямо сейчас"),
        ("todavía", "still/yet", "ещё"),
        ("ya", "already", "уже"),
        ("otra vez", "again", "снова"),
        ("en este momento", "at this moment", "в этот момент"),
        ("el mercado", "market", "рынок"),
        ("la tienda", "store", "магазин"),
        ("el banco", "bank", "банк"),
        ("el hospital", "hospital", "больница"),
        ("la farmacia", "pharmacy", "аптека"),
        ("el supermercado", "supermarket", "супермаркет"),
        ("la estación", "station", "станция"),
        ("el aeropuerto", "airport", "аэропорт"),
        ("cerca", "near", "близко"),
        ("lejos", "far", "далеко"),
        ("a la derecha", "to the right", "направо"),
        ("a la izquierda", "to the left", "налево"),
        ("derecho", "straight ahead", "прямо"),
        ("¿Dónde está...?", "Where is...?", "Где...?"),
        ("Está cerca de aquí.", "It's near here.", "Это близко отсюда."),
        ("Vamos juntos.", "Let's go together.", "Пойдём вместе."),
        ("Salgo a las ocho.", "I leave at eight.", "Я выхожу в восемь."),
    ],
    12: [
        ("fui", "I went", "я ходил"),
        ("fuiste", "you went", "ты ходил"),
        ("fue", "he/she went", "он/она ходил"),
        ("fuimos", "we went", "мы ходили"),
        ("fueron", "they went", "они ходили"),
        ("hice", "I did/made", "я сделал"),
        ("hiciste", "you did", "ты сделал"),
        ("hizo", "he/she did", "он/она сделал"),
        ("comí", "I ate", "я ел"),
        ("comiste", "you ate", "ты ел"),
        ("comió", "he/she ate", "он/она ел"),
        ("Ayer fui al cine.", "Yesterday I went to the cinema.", "Вчера я ходил в кино."),
        ("¿Qué hiciste ayer?", "What did you do yesterday?", "Что ты делал вчера?"),
        ("Fue muy bueno.", "It was very good.", "Было очень хорошо."),
        ("No fui.", "I didn't go.", "Я не ходил."),
        ("¿Cuándo fue?", "When was it?", "Когда это было?"),
        ("el pasado", "the past", "прошедшее"),
        ("el pretérito", "preterite tense", "претерит"),
        ("ayer por la mañana", "yesterday morning", "вчера утром"),
        ("anoche", "last night", "вчера вечером"),
        ("la semana pasada", "last week", "на прошлой неделе"),
        ("el mes pasado", "last month", "в прошлом месяце"),
        ("el año pasado", "last year", "в прошлом году"),
        ("una vez", "once", "однажды"),
        ("dos veces", "twice", "два раза"),
        ("muchas veces", "many times", "много раз"),
        ("siempre fui...", "I always was...", "Я всегда был..."),
        ("nunca fui...", "I never went...", "Я никогда не ходил..."),
        ("¿Fuiste a...?", "Did you go to...?", "Ты ходил в...?"),
        ("Comí tacos.", "I ate tacos.", "Я ел тако."),
        ("Hice la tarea.", "I did homework.", "Я сделал домашку."),
        ("Vi una película.", "I saw a movie.", "Я смотрел фильм."),
        ("vi", "I saw", "я видел"),
        ("dije", "I said", "я сказал"),
        ("estuve", "I was (temporary)", "я был (estar)"),
        ("estuve en casa", "I was at home", "я был дома"),
        ("¿Cómo fue tu día?", "How was your day?", "Как прошёл твой день?"),
    ],
    13: [
        ("voy a", "I'm going to", "я собираюсь"),
        ("va a", "he/she is going to", "он/она собирается"),
        ("iremos", "we will go", "мы пойдём"),
        ("mañana voy a...", "tomorrow I'm going to...", "завтра я..."),
        ("El próximo año...", "Next year...", "В следующем году..."),
        ("En el futuro...", "In the future...", "В будущем..."),
        ("quiero", "I want", "я хочу"),
        ("quieres", "you want", "ты хочешь"),
        ("quiere", "he/she wants", "он/она хочеет"),
        ("Quiero aprender más.", "I want to learn more.", "Хочу учиться дальше."),
        ("¿Qué quieres hacer?", "What do you want to do?", "Что хочешь делать?"),
        ("puedo", "I can", "я могу"),
        ("puedes", "you can", "ты можешь"),
        ("puede", "he/she can", "он/она может"),
        ("No puedo.", "I can't.", "Не могу."),
        ("¿Puedo ayudar?", "Can I help?", "Могу помочь?"),
        ("debo", "I must", "я должен"),
        ("debes", "you must", "ты должен"),
        ("Tengo que...", "I have to...", "Я должен..."),
        ("Hay que...", "One must...", "Нужно..."),
        ("el plan", "plan", "план"),
        ("el objetivo", "goal", "цель"),
        ("el sueño", "dream", "мечта"),
        ("la meta", "goal/target", "цель"),
        ("lograr", "to achieve", "достигать"),
        ("intentar", "to try", "пытаться"),
        ("empezar", "to begin", "начинать"),
        ("terminar", "to finish", "заканчивать"),
        ("continuar", "to continue", "продолжать"),
        ("practicar", "to practice", "практиковать"),
        ("mejorar", "to improve", "улучшать"),
        ("¡Felicidades!", "Congratulations!", "Поздравляю!"),
        ("Terminé A1.", "I finished A1.", "Я закончил A1."),
        ("Sigo aprendiendo.", "I keep learning.", "Продолжаю учиться."),
        ("Estoy listo.", "I'm ready (m).", "Я готов."),
        ("Estoy lista.", "I'm ready (f).", "Я готова."),
        ("¿Qué sigue?", "What's next?", "Что дальше?"),
        ("El siguiente nivel.", "The next level.", "Следующий уровень."),
    ],
}
