"""Rich A1 theory content: structured grammar, listen examples, and per-day focus (weeks 1–13)."""

from .program import t

# grammar_sections: titled blocks shown on the theory screen
# day_focus: per-day intro (keys 1–6)
# examples: full-sentence listen pool for the week


def _gs(sections_ru, sections_en, sections_es):
    return {"ru": sections_ru, "en": sections_en, "es": sections_es}


def _ex(es, en, ru):
    return {"es": es, "en": en, "ru": ru}


A1_THEORY = {
    1: {
        "grammar_sections": _gs(
            [
                {"title": "Приветствия по времени суток", "text": "Buenos días (до ~14:00), buenas tardes (день/вечер), buenas noches (прощание вечером или «спокойной ночи»). В Мексике часто просто «Hola» в любое время."},
                {"title": "Личные местоимения", "text": "yo (я), tú (ты), él/ella (он/она), nosotros (мы), ustedes (вы — всегда мн.ч.), ellos/ellas (они). Местоимение можно опускать: «Hablo» = «Я говорю»."},
                {"title": "Ustedes в Мексике", "text": "В Мексике ustedes — единственная форма «вы» во множественном числе. Испанского vosotros здесь нет. Usted (Вы) — вежливое единственное «вы»."},
                {"title": "Знакомство", "text": "¿Cómo te llamas? — «Как тебя зовут?» (неформально). Me llamo… — «Меня зовут…». Mucho gusto — «Приятно познакомиться»."},
                {"title": "Как дела?", "text": "¿Cómo estás? — неформально. ¿Cómo está usted? — вежливо. Ответ: Estoy bien, gracias. ¿Y tú? — «А ты?»"},
            ],
            [
                {"title": "Greetings by time of day", "text": "Buenos días (until ~2pm), buenas tardes (afternoon/evening), buenas noches (goodbye at night). In Mexico people often just say Hola anytime."},
                {"title": "Subject pronouns", "text": "yo, tú, él/ella, nosotros, ustedes, ellos/ellas. You can drop the pronoun: Hablo already means 'I speak'."},
                {"title": "Ustedes in Mexico", "text": "In Mexico ustedes is the only plural 'you'. There is no vosotros. Usted is the formal singular 'you'."},
                {"title": "Introductions", "text": "¿Cómo te llamas? (informal). Me llamo… = My name is…. Mucho gusto = Nice to meet you."},
                {"title": "How are you?", "text": "¿Cómo estás? (informal). ¿Cómo está usted? (formal). Reply: Estoy bien, gracias. ¿Y tú?"},
            ],
            [
                {"title": "Saludos según la hora", "text": "Buenos días, buenas tardes, buenas noches. En México mucha gente dice solo Hola."},
                {"title": "Pronombres personales", "text": "yo, tú, él/ella, nosotros, ustedes, ellos/ellas. Puedes omitir el pronombre."},
                {"title": "Ustedes en México", "text": "En México ustedes es el único plural de 'tú'. No hay vosotros."},
                {"title": "Presentaciones", "text": "¿Cómo te llamas? Me llamo… Mucho gusto."},
                {"title": "¿Cómo estás?", "text": "¿Cómo estás? / ¿Cómo está usted? Estoy bien, gracias. ¿Y tú?"},
            ],
        ),
        "examples": [
            _ex("Hola, ¿qué tal?", "Hi, how's it going?", "Привет, как дела?"),
            _ex("Buenos días, mucho gusto.", "Good morning, nice to meet you.", "Доброе утро, приятно познакомиться."),
            _ex("Me llamo Ana. ¿Y tú?", "My name is Ana. And you?", "Меня зовут Ана. А ты?"),
            _ex("¿Cómo estás? — Estoy bien, gracias.", "How are you? — I'm fine, thanks.", "Как ты? — Я в порядке, спасибо."),
            _ex("Nosotros somos de México.", "We are from Mexico.", "Мы из Мексики."),
            _ex("Hasta luego, nos vemos.", "See you later.", "До скорого, увидимся."),
        ],
        "day_focus": {
            1: t("Day 1 — greetings: hola, buenos días, buenas tardes, buenas noches. Listen and repeat every phrase.",
                 "День 1 — приветствия: hola, buenos días, buenas tardes, buenas noches. Прослушайте и повторите каждую фразу.",
                 "Día 1 — saludos: hola, buenos días, buenas tardes, buenas noches."),
            2: t("Day 2 — pronouns yo, tú, él, ella. Learn who is who in a sentence.",
                 "День 2 — местоимения yo, tú, él, ella. Учимся различать «я, ты, он, она».",
                 "Día 2 — pronombres yo, tú, él, ella."),
            3: t("Day 3 — nosotros, ustedes, ellos. In Mexico ustedes = all plural 'you'.",
                 "День 3 — nosotros, ustedes, ellos. В Мексике ustedes = любое «вы» во мн. числе.",
                 "Día 3 — nosotros, ustedes, ellos."),
            4: t("Day 4 — politeness: por favor, gracias, de nada, sí, no.",
                 "День 4 — вежливость: por favor, gracias, de nada, sí, no.",
                 "Día 4 — cortesía: por favor, gracias, de nada."),
            5: t("Day 5 — introductions: ¿cómo te llamas?, me llamo…, mucho gusto.",
                 "День 5 — знакомство: ¿cómo te llamas?, me llamo…, mucho gusto.",
                 "Día 5 — presentaciones: ¿cómo te llamas?, me llamo…"),
            6: t("Day 6 — put it together: greetings + how are you + goodbye. You're ready to say hello in Mexico!",
                 "День 6 — собираем всё: приветствие + как дела + прощание. Вы уже можете поздороваться в Мексике!",
                 "Día 6 — une todo: saludo + ¿cómo estás? + despedida."),
        },
    },
    2: {
        "grammar_sections": _gs(
            [
                {"title": "Числа 1–15", "text": "uno, dos, tres… quince — учим наизусть. Они нужны везде: возраст, цена, время."},
                {"title": "Числа 16–29", "text": "Пишутся одним словом: dieciséis (16), veintiuno (21), veintidós (22). Это особенность испанского."},
                {"title": "Род существительных", "text": "Обычно -o = мужской (el libro), -a = женский (la casa). Исключения встретятся позже — пока запоминайте вместе со словом."},
                {"title": "Артикли el / la / los / las", "text": "el (м.р.), la (ж.р.), los/las (мн.ч.). Артикль почти всегда нужен: «книга» = el libro, не просто libro."},
                {"title": "Множественное число", "text": "К -o/-a/-e обычно +s: libro → libros, casa → casas. На согласную +es: papel → papeles."},
            ],
            [
                {"title": "Numbers 1–15", "text": "uno through quince — memorize them; you need them for age, prices, time."},
                {"title": "Numbers 16–29", "text": "Written as one word: dieciséis, veintiuno, veintidós."},
                {"title": "Noun gender", "text": "Usually -o = masculine, -a = feminine. Learn each noun with its article."},
                {"title": "Articles el / la / los / las", "text": "Almost always required: el libro, la casa."},
                {"title": "Plurals", "text": "Usually add -s or -es: libros, casas, papeles."},
            ],
            [
                {"title": "Números 1–15", "text": "uno… quince — memorízalos."},
                {"title": "Números 16–29", "text": "Se escriben juntos: dieciséis, veintiuno."},
                {"title": "Género", "text": "-o suele ser masculino, -a femenino."},
                {"title": "Artículos", "text": "el, la, los, las."},
                {"title": "Plural", "text": "-s o -es: libros, casas."},
            ],
        ),
        "examples": [
            _ex("Tengo veinte años.", "I'm twenty years old.", "Мне двадцать лет."),
            _ex("Quiero dos tacos, por favor.", "I want two tacos, please.", "Два тако, пожалуйста."),
            _ex("La casa es grande.", "The house is big.", "Дом большой."),
            _ex("Los libros son nuevos.", "The books are new.", "Книги новые."),
            _ex("Cinco más tres son ocho.", "Five plus three is eight.", "Пять плюс три — восемь."),
            _ex("¿Cuántos tacos quieres?", "How many tacos do you want?", "Сколько тако хочешь?"),
        ],
        "day_focus": {
            1: t("Day 1 — numbers 1–10: count out loud in Spanish.",
                 "День 1 — числа 1–10: считайте вслух по-испански.",
                 "Día 1 — números 1–10."),
            2: t("Day 2 — numbers 11–20 and veinte, treinta, cien.",
                 "День 2 — числа 11–20 и veinte, treinta, cien.",
                 "Día 2 — números 11–20."),
            3: t("Day 3 — articles el, la, los, las with nouns.",
                 "День 3 — артикли el, la, los, las со словами.",
                 "Día 3 — artículos el, la, los, las."),
            4: t("Day 4 — masculine nouns: el libro, el taco…",
                 "День 4 — существительные м.р.: el libro, el taco…",
                 "Día 4 — sustantivos masculinos."),
            5: t("Day 5 — feminine nouns: la casa, la mesa…",
                 "День 5 — существительные ж.р.: la casa, la mesa…",
                 "Día 5 — sustantivos femeninos."),
            6: t("Day 6 — numbers + articles in real phrases. Practice Tengo … años.",
                 "День 6 — числа + артикли в фразах. Потренируйте Tengo … años.",
                 "Día 6 — números y artículos en frases."),
        },
    },
    3: {
        "grammar_sections": _gs(
            [
                {"title": "Два глагола «быть»", "text": "Ser — суть, профессия, происхождение, постоянные качества. Estar — место, настроение, временное состояние."},
                {"title": "Спряжение SER", "text": "soy, eres, es, somos, son. Yo soy mexicano. Él es profesor."},
                {"title": "Спряжение ESTAR", "text": "estoy, estás, está, estamos, están. Estoy en casa. Está cansada."},
                {"title": "Быстрое правило", "text": "Может быстро измениться (место, усталость, настроение) → estar. Определяет личность → ser."},
                {"title": "Вопросы", "text": "¿Quién? (кто) → ser. ¿Dónde? (где) → estar. ¿Cómo estás? — о самочувствии."},
            ],
            [
                {"title": "Two 'to be' verbs", "text": "Ser = identity, origin, traits. Estar = location, mood, temporary state."},
                {"title": "SER conjugation", "text": "soy, eres, es, somos, son."},
                {"title": "ESTAR conjugation", "text": "estoy, estás, está, estamos, están."},
                {"title": "Quick rule", "text": "Can change soon → estar. Defines you → ser."},
                {"title": "Questions", "text": "¿Quién? → ser. ¿Dónde? → estar."},
            ],
            [
                {"title": "Dos verbos 'ser' y 'estar'", "text": "Ser = identidad. Estar = lugar y estado."},
                {"title": "SER", "text": "soy, eres, es, somos, son."},
                {"title": "ESTAR", "text": "estoy, estás, está, estamos, están."},
                {"title": "Regla rápida", "text": "Cambia pronto → estar. Te define → ser."},
                {"title": "Preguntas", "text": "¿Quién? / ¿Dónde?"},
            ],
        ),
        "examples": [
            _ex("Yo soy de México.", "I'm from Mexico.", "Я из Мексики."),
            _ex("Ella está cansada hoy.", "She's tired today.", "Она сегодня устала."),
            _ex("Estamos en casa.", "We're at home.", "Мы дома."),
            _ex("Él es mi amigo.", "He's my friend.", "Он мой друг."),
            _ex("¿Dónde estás?", "Where are you?", "Где ты?"),
            _ex("Son las tres de la tarde.", "It's three in the afternoon.", "Три часа дня."),
        ],
        "day_focus": {
            1: t("Day 1 — SER forms: soy, eres, es.",
                 "День 1 — формы SER: soy, eres, es.",
                 "Día 1 — SER: soy, eres, es."),
            2: t("Day 2 — ESTAR forms: estoy, estás, está.",
                 "День 2 — формы ESTAR: estoy, estás, está.",
                 "Día 2 — ESTAR: estoy, estás, está."),
            3: t("Day 3 — origin & identity with ser: soy de…, es profesor.",
                 "День 3 — происхождение и сущность с ser.",
                 "Día 3 — origen con ser."),
            4: t("Day 4 — location & feelings with estar: aquí, allá, cansado, feliz.",
                 "День 4 — место и состояние с estar.",
                 "Día 4 — lugar con estar."),
            5: t("Day 5 — plural: somos, son, estamos, están.",
                 "День 5 — множественное число: somos, son, estamos, están.",
                 "Día 5 — plural: somos, están."),
            6: t("Day 6 — choose ser or estar in every sentence. This is the heart of Spanish!",
                 "День 6 — в каждой фразе выбирайте ser или estar. Это сердце испанского!",
                 "Día 6 — elige ser o estar."),
        },
    },
    4: {
        "grammar_sections": _gs(
            [
                {"title": "Слова о семье", "text": "mamá/papá (разг.), madre/padre (нейтр.), hermano/hermana, hijo/hija, abuelo/abuela, tío/tía."},
                {"title": "Притяжательные", "text": "mi (мой), tu (твой), su (его/её/их/Ваш), nuestro/nuestra (наш). Согласуются в числе: mis hermanos, nuestra casa."},
                {"title": "Su = много значений", "text": "su hermano = его/её/их/Ваш брат — смысл ясен из контекста."},
                {"title": "Мексиканское тепло", "text": "mijo/mija — ласково «сынок/дочка», часто не только к детям. «¿Cómo está, mijo?»"},
                {"title": "Спросить о семье", "text": "¿Cuántos hermanos tienes? — Сколько у тебя братьев/сестёр? Tengo dos hermanos."},
            ],
            [
                {"title": "Family words", "text": "mamá, papá, hermano, hermana, hijo, hija, abuelo, abuela, tío, tía."},
                {"title": "Possessives", "text": "mi, tu, su, nuestro/nuestra. Agree in number: mis hermanos."},
                {"title": "Su is ambiguous", "text": "su hermano = his/her/their/your brother — context clarifies."},
                {"title": "Mexican warmth", "text": "mijo/mija = affectionate 'son/daughter'."},
                {"title": "Asking about family", "text": "¿Cuántos hermanos tienes?"},
            ],
            [
                {"title": "Familia", "text": "mamá, papá, hermano, hermana…"},
                {"title": "Posesivos", "text": "mi, tu, su, nuestro/nuestra."},
                {"title": "Su", "text": "Puede ser his/her/their/your."},
                {"title": "mijo/mija", "text": "Carino mexicano."},
                {"title": "Preguntas", "text": "¿Cuántos hermanos tienes?"},
            ],
        ),
        "examples": [
            _ex("Mi mamá se llama Rosa.", "My mom's name is Rosa.", "Мою маму зовут Роса."),
            _ex("¿Cuántos hermanos tienes?", "How many siblings do you have?", "Сколько у тебя братьев/сестёр?"),
            _ex("Nuestra casa es bonita.", "Our house is pretty.", "Наш дом красивый."),
            _ex("Mi familia es grande.", "My family is big.", "У меня большая семья."),
            _ex("El tío de mi papá es mi tío abuelo.", "My dad's uncle is my great-uncle.", "Дядя моего папы — мой прадядя."),
            _ex("¿Cómo está, mijo?", "How are you, son? (affectionate)", "Как дела, сынок? (ласково)"),
        ],
        "day_focus": {
            1: t("Day 1 — parents & children: mamá, papá, hijo, hija.",
                 "День 1 — родители и дети: mamá, papá, hijo, hija.",
                 "Día 1 — padres e hijos."),
            2: t("Day 2 — siblings: hermano, hermana.",
                 "День 2 — братья и сёстры.",
                 "Día 2 — hermanos."),
            3: t("Day 3 — grandparents & extended family: abuelo, abuela, tío, tía.",
                 "День 3 — бабушки, дедушки, дяди, тёти.",
                 "Día 3 — abuelos y tíos."),
            4: t("Day 4 — possessives mi, tu, su.",
                 "День 4 — притяжательные mi, tu, su.",
                 "Día 4 — mi, tu, su."),
            5: t("Day 5 — nuestro/nuestra and describing family.",
                 "День 5 — nuestro/nuestra и описание семьи.",
                 "Día 5 — nuestro, nuestra."),
            6: t("Day 6 — talk about your family in full sentences.",
                 "День 6 — расскажите о своей семье целыми фразами.",
                 "Día 6 — habla de tu familia."),
        },
    },
    5: {
        "grammar_sections": _gs(
            [
                {"title": "Me gusta / Me gustan", "text": "Me gusta + ед.ч. (Me gusta el taco). Me gustan + мн.ч. (Me gustan los tacos). Буквально: «мне нравится»."},
                {"title": "Quiero + существительное", "text": "Quiero un taco, quiero agua. Артикль или un/una обычно нужен."},
                {"title": "В ресторане", "text": "¿Qué quieres comer? La cuenta, por favor. ¿Cuánto cuesta?"},
                {"title": "Еда в Мексике", "text": "taco, tortilla, salsa, limón (лайм), picante. «¿Con todo?» — с луком и кинзой."},
                {"title": "Голод и жажда", "text": "Tengo hambre (я голоден), tengo sed (хочу пить) — через глагол tener, не ser/estar."},
            ],
            [
                {"title": "Me gusta / Me gustan", "text": "Singular vs plural: Me gusta el taco / Me gustan los tacos."},
                {"title": "Quiero", "text": "Quiero un taco. Use un/una or the article."},
                {"title": "At the restaurant", "text": "¿Qué quieres comer? La cuenta, por favor."},
                {"title": "Mexican food", "text": "taco, salsa, limón. ¿Con todo?"},
                {"title": "Hunger & thirst", "text": "Tengo hambre, tengo sed — use tener."},
            ],
            [
                {"title": "Me gusta / gustan", "text": "Singular y plural."},
                {"title": "Quiero", "text": "Quiero un taco."},
                {"title": "En el restaurante", "text": "La cuenta, por favor."},
                {"title": "Comida mexicana", "text": "taco, salsa, ¿con todo?"},
                {"title": "Hambre y sed", "text": "Tengo hambre, tengo sed."},
            ],
        ),
        "examples": [
            _ex("Me gustan los tacos al pastor.", "I like al pastor tacos.", "Мне нравятся тако аль пастор."),
            _ex("Quiero un café, por favor.", "A coffee, please.", "Кофе, пожалуйста."),
            _ex("¿Con todo?", "With everything? (onion & cilantro)", "Со всем? (лук и кинза)"),
            _ex("La salsa está muy picante.", "The salsa is very spicy.", "Соус очень острый."),
            _ex("Tengo hambre, ¿qué hay de comer?", "I'm hungry, what's there to eat?", "Я голоден, что есть поесть?"),
            _ex("La cuenta, por favor.", "The bill, please.", "Счёт, пожалуйста."),
        ],
        "day_focus": {
            1: t("Day 1 — basic food words: taco, tortilla, salsa, agua.",
                 "День 1 — базовая еда: taco, tortilla, salsa, agua.",
                 "Día 1 — comida básica."),
            2: t("Day 2 — me gusta / me gustan.",
                 "День 2 — me gusta / me gustan.",
                 "Día 2 — me gusta / gustan."),
            3: t("Day 3 — quiero, un/una, ordering.",
                 "День 3 — quiero, заказ в кафе.",
                 "Día 3 — quiero y pedir."),
            4: t("Day 4 — drinks, picante, rico, delicioso.",
                 "День 4 — напитки и вкус: picante, rico.",
                 "Día 4 — bebidas y sabor."),
            5: t("Day 5 — tengo hambre/sed, la cuenta.",
                 "День 5 — голод, жажда, счёт.",
                 "Día 5 — hambre, sed, cuenta."),
            6: t("Day 6 — order a full meal in Spanish!",
                 "День 6 — закажите полноценный обед по-испански!",
                 "Día 6 — pide una comida completa."),
        },
    },
    6: {
        "grammar_sections": _gs(
            [
                {"title": "Глаголы на -AR", "text": "hablar, trabajar, estudiar, cocinar… Самая большая группа глаголов."},
                {"title": "Окончания настоящего", "text": "Убираем -ar, добавляем: -o (yo), -as (tú), -a (él), -amos (nosotros), -an (ellos)."},
                {"title": "Пример: hablar", "text": "hablo, hablas, habla, hablamos, hablan. Yo hablo español."},
                {"title": "Местоимение можно не говорить", "text": "Hablo = я говорю. Окончание уже показывает лицо."},
                {"title": "Отрицание", "text": "no перед глаголом: No hablo inglés. No trabajo hoy."},
            ],
            [
                {"title": "-AR verbs", "text": "hablar, trabajar, estudiar — largest verb group."},
                {"title": "Present endings", "text": "Remove -ar, add -o, -as, -a, -amos, -an."},
                {"title": "Example: hablar", "text": "hablo, hablas, habla, hablamos, hablan."},
                {"title": "Drop the pronoun", "text": "Hablo already means 'I speak'."},
                {"title": "Negation", "text": "no before the verb: No hablo inglés."},
            ],
            [
                {"title": "Verbos -AR", "text": "hablar, trabajar, estudiar."},
                {"title": "Presente", "text": "-o, -as, -a, -amos, -an."},
                {"title": "hablar", "text": "hablo, hablas, habla…"},
                {"title": "Sin pronombre", "text": "Hablo = yo hablo."},
                {"title": "Negación", "text": "No hablo."},
            ],
        ),
        "examples": [
            _ex("Yo hablo español todos los días.", "I speak Spanish every day.", "Я говорю по-испански каждый день."),
            _ex("Ella trabaja en la escuela.", "She works at school.", "Она работает в школе."),
            _ex("Nosotros estudiamos mucho.", "We study a lot.", "Мы много учимся."),
            _ex("¿Hablas inglés?", "Do you speak English?", "Ты говоришь по-английски?"),
            _ex("No cocino hoy.", "I'm not cooking today.", "Сегодня я не готовлю."),
            _ex("Me gusta escuchar música.", "I like listening to music.", "Мне нравится слушать музыку."),
        ],
        "day_focus": {
            1: t("Day 1 — infinitives -AR: hablar, trabajar, estudiar.",
                 "День 1 — инфинитивы на -AR.",
                 "Día 1 — infinitivos -AR."),
            2: t("Day 2 — yo form (-o): hablo, trabajo, estudio.",
                 "День 2 — форма yo (-o).",
                 "Día 2 — forma yo."),
            3: t("Day 3 — tú/él forms (-as/-a).",
                 "День 3 — формы tú и él/ella.",
                 "Día 3 — tú y él/ella."),
            4: t("Day 4 — nosotros (-amos) and daily verbs.",
                 "День 4 — nosotros (-amos).",
                 "Día 4 — nosotros."),
            5: t("Day 5 — negation with no.",
                 "День 5 — отрицание с no.",
                 "Día 5 — negación."),
            6: t("Day 6 — conjugate -AR verbs in full sentences.",
                 "День 6 — спрягайте -AR в целых фразах.",
                 "Día 6 — conjuga verbos -AR."),
        },
    },
    7: {
        "grammar_sections": _gs(
            [
                {"title": "Глаголы -ER", "text": "comer, beber, leer, aprender. Окончания: -o, -es, -e, -emos, -en."},
                {"title": "Глаголы -IR", "text": "vivir, escribir, abrir. Те же окончания, кроме nosotros: -imos (vivimos)."},
                {"title": "comer → como, comes, come", "text": "Como tacos. ¿Qué comes?"},
                {"title": "vivir → vivo, vives, vive", "text": "Vivo en México. ¿Dónde vives?"},
                {"title": "Разница -emos / -imos", "text": "comemos (мы едим) vs vivimos (мы живём) — единственное отличие между -ER и -IR."},
            ],
            [
                {"title": "-ER verbs", "text": "comer, beber, leer. Endings: -o, -es, -e, -emos, -en."},
                {"title": "-IR verbs", "text": "vivir, escribir. Same except nosotros: -imos."},
                {"title": "comer", "text": "como, comes, come, comemos, comen."},
                {"title": "vivir", "text": "vivo, vives, vive, vivimos, viven."},
                {"title": "-emos vs -imos", "text": "The only difference in 'we' form."},
            ],
            [
                {"title": "Verbos -ER", "text": "comer, beber, leer."},
                {"title": "Verbos -IR", "text": "vivir, escribir."},
                {"title": "comer", "text": "como, comes, come."},
                {"title": "vivir", "text": "vivo, vives, vive."},
                {"title": "-emos / -imos", "text": "comemos vs vivimos."},
            ],
        ),
        "examples": [
            _ex("Como tacos todos los días.", "I eat tacos every day.", "Я ем тако каждый день."),
            _ex("¿Dónde vives?", "Where do you live?", "Где ты живёшь?"),
            _ex("Ella lee un libro.", "She reads a book.", "Она читает книгу."),
            _ex("Bebo agua, no bebo refresco.", "I drink water, not soda.", "Я пью воду, не газировку."),
            _ex("Nosotros aprendemos español.", "We learn Spanish.", "Мы учим испанский."),
            _ex("Escribo una carta a mi mamá.", "I write a letter to my mom.", "Я пишу письмо маме."),
        ],
        "day_focus": {
            1: t("Day 1 — -ER verbs: comer, beber, leer.",
                 "День 1 — глаголы -ER.",
                 "Día 1 — verbos -ER."),
            2: t("Day 2 — -IR verbs: vivir, escribir.",
                 "День 2 — глаголы -IR.",
                 "Día 2 — verbos -IR."),
            3: t("Day 3 — como, comes, come (eating).",
                 "День 3 — спряжение comer.",
                 "Día 3 — comer."),
            4: t("Day 4 — vivo, vives, vive (living).",
                 "День 4 — спряжение vivir.",
                 "Día 4 — vivir."),
            5: t("Day 5 — questions with ¿dónde?, ¿qué?",
                 "День 5 — вопросы с ¿dónde?, ¿qué?",
                 "Día 5 — preguntas."),
            6: t("Day 6 — mix -AR, -ER, -IR in one conversation.",
                 "День 6 — смешивайте -AR, -ER, -IR в одном разговоре.",
                 "Día 6 — mezcla -AR, -ER, -IR."),
        },
    },
    8: {
        "grammar_sections": _gs(
            [
                {"title": "Время", "text": "¿Qué hora es? Es la una (1:00). Son las dos (2:00+). Siempre «las» с 2 до 12."},
                {"title": "Дни недели", "text": "lunes… domingo — с маленькой буквы. Hoy es lunes. Mañana es martes."},
                {"title": "Части дня", "text": "la mañana (утро), la tarde (день/вечер), la noche (ночь). Buenas tardes ≠ la tarde."},
                {"title": "Месяцы", "text": "enero… diciembre. Mi cumpleaños es en mayo. El 5 de mayo."},
                {"title": "Ahorita (Мексика)", "text": "«Прямо сейчас»… или «чуть позже». Контекст решает — типично по-мексикански!" },
            ],
            [
                {"title": "Telling time", "text": "¿Qué hora es? Es la una. Son las dos."},
                {"title": "Days", "text": "lunes–domingo, lowercase. Hoy es lunes."},
                {"title": "Parts of day", "text": "la mañana, la tarde, la noche."},
                {"title": "Months", "text": "enero–diciembre. en mayo."},
                {"title": "Ahorita (Mexico)", "text": "Right now… or maybe later. Very Mexican!"},
            ],
            [
                {"title": "La hora", "text": "Es la una. Son las dos."},
                {"title": "Días", "text": "lunes… domingo."},
                {"title": "Mañana, tarde, noche", "text": "Partes del día."},
                {"title": "Meses", "text": "enero… diciembre."},
                {"title": "Ahorita", "text": "Ahora… o después."},
            ],
        ),
        "examples": [
            _ex("¿Qué hora es? — Son las tres.", "What time is it? — It's three.", "Который час? — Три."),
            _ex("Hoy es viernes.", "Today is Friday.", "Сегодня пятница."),
            _ex("Mañana es sábado.", "Tomorrow is Saturday.", "Завтра суббота."),
            _ex("Mi cumpleaños es en julio.", "My birthday is in July.", "Мой день рождения в июле."),
            _ex("Nos vemos en la tarde.", "See you in the afternoon.", "Увидимся днём."),
            _ex("Ahorita regreso.", "I'll be right back. (Mex.)", "Сейчас вернусь. (мекс.)"),
        ],
        "day_focus": {
            1: t("Day 1 — days of the week lunes… domingo.",
                 "День 1 — дни недели.",
                 "Día 1 — días de la semana."),
            2: t("Day 2 — hoy, mañana, ayer.",
                 "День 2 — сегодня, завтра, вчера.",
                 "Día 2 — hoy, mañana, ayer."),
            3: t("Day 3 — telling time: ¿qué hora es?",
                 "День 3 — как сказать время.",
                 "Día 3 — la hora."),
            4: t("Day 4 — morning, afternoon, night.",
                 "День 4 — утро, день, ночь.",
                 "Día 4 — mañana, tarde, noche."),
            5: t("Day 5 — months and dates.",
                 "День 5 — месяцы и даты.",
                 "Día 5 — meses."),
            6: t("Day 6 — describe your weekly schedule.",
                 "День 6 — опишите своё недельное расписание.",
                 "Día 6 — tu horario semanal."),
        },
    },
    9: {
        "grammar_sections": _gs(
            [
                {"title": "Прилагательные после существительного", "text": "un coche rojo (красная машина), una casa grande. Порядок обратный русскому."},
                {"title": "Согласование", "text": "rojo/roja/rojos/rojas. alto/alta, bonito/bonita — по роду и числу."},
                {"title": "Цвета", "text": "rojo, azul, verde, amarillo, negro, blanco — запоминайте с родом."},
                {"title": "Описание", "text": "Es alto, es fácil, es importante. С ser для постоянных качеств."},
                {"title": "Мексика: padre / chido", "text": "Оба значат «классно!». ¡Qué padre! = ¡Qué chido!"},
            ],
            [
                {"title": "Adjective after noun", "text": "un coche rojo, una casa grande."},
                {"title": "Agreement", "text": "rojo/roja/rojos/rojas."},
                {"title": "Colors", "text": "rojo, azul, verde…"},
                {"title": "Describing", "text": "Es alto, es fácil — with ser."},
                {"title": "Mexico: padre / chido", "text": "Both mean 'cool!'"},
            ],
            [
                {"title": "Adjetivo después", "text": "coche rojo, casa grande."},
                {"title": "Concordancia", "text": "rojo/roja."},
                {"title": "Colores", "text": "rojo, azul, verde."},
                {"title": "Descripción", "text": "Es alto, es fácil."},
                {"title": "padre / chido", "text": "¡Qué padre!"},
            ],
        ),
        "examples": [
            _ex("Tengo un coche rojo.", "I have a red car.", "У меня красная машина."),
            _ex("Es una casa muy grande.", "It's a very big house.", "Это очень большой дом."),
            _ex("Los tacos están muy ricos.", "The tacos are very tasty.", "Тако очень вкусные."),
            _ex("¡Qué padre!", "How cool!", "Как классно!"),
            _ex("El español es fácil.", "Spanish is easy.", "Испанский лёгкий."),
            _ex("Es un libro nuevo.", "It's a new book.", "Это новая книга."),
        ],
        "day_focus": {
            1: t("Day 1 — colors: rojo, azul, verde…",
                 "День 1 — цвета.",
                 "Día 1 — colores."),
            2: t("Day 2 — size & quality: grande, pequeño, bueno, malo.",
                 "День 2 — размер и качество.",
                 "Día 2 — tamaño y calidad."),
            3: t("Day 3 — agreement: rojo/roja, nuevo/nueva.",
                 "День 3 — согласование прилагательных.",
                 "Día 3 — concordancia."),
            4: t("Day 4 — bonito, feo, fácil, difícil.",
                 "День 4 — описание вещей.",
                 "Día 4 — descripción."),
            5: t("Day 5 — Mexican slang: chido, padre.",
                 "День 5 — мексиканский сленг: chido, padre.",
                 "Día 5 — chido, padre."),
            6: t("Day 6 — describe three things around you.",
                 "День 6 — опишите три предмета вокруг.",
                 "Día 6 — describe tres cosas."),
        },
    },
    10: {
        "grammar_sections": _gs(
            [
                {"title": "Глагол tener", "text": "tengo, tienes, tiene, tenemos, tienen — «иметь», но часто «у меня есть»."},
                {"title": "Возраст", "text": "Tengo 25 años — буквально «у меня 25 лет». Не soy 25!" },
                {"title": "Состояния с tener", "text": "tener hambre/sed/frío/calor/sueño — голод, жажда, холод, жара, сонливость."},
                {"title": "Выражения", "text": "tener razón (быть правым), tener prisa (спешить), tener miedo (бояться)."},
                {"title": "Вопросы", "text": "¿Cuántos años tienes? ¿Tienes hambre? ¿Tienes tiempo?"},
            ],
            [
                {"title": "Tener", "text": "tengo, tienes, tiene, tenemos, tienen."},
                {"title": "Age", "text": "Tengo 25 años — not soy."},
                {"title": "States", "text": "tener hambre, sed, frío, calor, sueño."},
                {"title": "Expressions", "text": "tener razón, prisa, miedo."},
                {"title": "Questions", "text": "¿Cuántos años tienes?"},
            ],
            [
                {"title": "Tener", "text": "tengo, tienes, tiene."},
                {"title": "Edad", "text": "Tengo 25 años."},
                {"title": "Estados", "text": "hambre, sed, frío."},
                {"title": "Expresiones", "text": "razón, prisa, miedo."},
                {"title": "Preguntas", "text": "¿Cuántos años tienes?"},
            ],
        ),
        "examples": [
            _ex("Tengo veinticinco años.", "I'm 25 years old.", "Мне 25 лет."),
            _ex("¿Cuántos años tienes?", "How old are you?", "Сколько тебе лет?"),
            _ex("Tengo mucha hambre.", "I'm very hungry.", "Я очень голоден."),
            _ex("¿Tienes frío?", "Are you cold?", "Тебе холодно?"),
            _ex("Tenemos prisa.", "We're in a hurry.", "Мы спешим."),
            _ex("Tienes razón.", "You're right.", "Ты прав."),
        ],
        "day_focus": {
            1: t("Day 1 — tener conjugation.",
                 "День 1 — спряжение tener.",
                 "Día 1 — tener."),
            2: t("Day 2 — age: tengo … años.",
                 "День 2 — возраст.",
                 "Día 2 — edad."),
            3: t("Day 3 — hunger, thirst, cold, heat.",
                 "День 3 — голод, жажда, холод, жара.",
                 "Día 3 — hambre, sed, frío."),
            4: t("Day 4 — sleepiness, hurry, fear.",
                 "День 4 — сон, спешка, страх.",
                 "Día 4 — sueño, prisa, miedo."),
            5: t("Day 5 — tener razón, tener tiempo.",
                 "День 5 — быть правым, иметь время.",
                 "Día 5 — razón, tiempo."),
            6: t("Day 6 — ask and answer about age and feelings.",
                 "День 6 — спрашивайте о возрасте и самочувствии.",
                 "Día 6 — edad y estados."),
        },
    },
    11: {
        "grammar_sections": _gs(
            [
                {"title": "Глагол ir", "text": "voy, vas, va, vamos, van — «идти/ехать»."},
                {"title": "Ближайшее будущее", "text": "ir + a + инфинитив: voy a comer = собираюсь есть. Vas a estudiar."},
                {"title": "a + el = al", "text": "Voy al mercado (al = a + el). Voy a la escuela."},
                {"title": "Сейчас (герундий)", "text": "estar + -ando/-iendo: estoy hablando, está comiendo."},
                {"title": "Вопрос", "text": "¿Qué estás haciendo? — «Что делаешь?» Estoy trabajando."},
            ],
            [
                {"title": "Ir", "text": "voy, vas, va, vamos, van."},
                {"title": "Near future", "text": "ir + a + infinitive: voy a comer."},
                {"title": "al", "text": "a + el = al. Voy al mercado."},
                {"title": "Present continuous", "text": "estar + gerund: estoy hablando."},
                {"title": "¿Qué estás haciendo?", "text": "What are you doing right now?"},
            ],
            [
                {"title": "Ir", "text": "voy, vas, va."},
                {"title": "Futuro próximo", "text": "voy a + infinitivo."},
                {"title": "al", "text": "Voy al mercado."},
                {"title": "Gerundio", "text": "estoy hablando."},
                {"title": "¿Qué haces?", "text": "¿Qué estás haciendo?"},
            ],
        ),
        "examples": [
            _ex("Voy a estudiar mañana.", "I'm going to study tomorrow.", "Завтра буду учиться."),
            _ex("¿Vas al mercado?", "Are you going to the market?", "Ты идёшь на рынок?"),
            _ex("Estoy comiendo tacos.", "I'm eating tacos right now.", "Я ем тако (сейчас)."),
            _ex("¿Qué estás haciendo?", "What are you doing?", "Что ты делаешь?"),
            _ex("Vamos al cine.", "Let's go to the cinema.", "Пойдём в кино."),
            _ex("Ella está trabajando.", "She's working right now.", "Она сейчас работает."),
        ],
        "day_focus": {
            1: t("Day 1 — ir: voy, vas, va.",
                 "День 1 — глагол ir.",
                 "Día 1 — ir."),
            2: t("Day 2 — voy a + verb (near future).",
                 "День 2 — ближайшее будущее voy a…",
                 "Día 2 — voy a + infinitivo."),
            3: t("Day 3 — places: mercado, escuela, parque, al/a la.",
                 "День 3 — места и al/a la.",
                 "Día 3 — lugares."),
            4: t("Day 4 — gerund -ando: hablando, comiendo.",
                 "День 4 — герундий -ando.",
                 "Día 4 — gerundio -ando."),
            5: t("Day 5 — gerund -iendo: viviendo, haciendo.",
                 "День 5 — герундий -iendo.",
                 "Día 5 — -iendo."),
            6: t("Day 6 — plans (voy a…) + what you're doing now (estoy…).",
                 "День 6 — планы и «что делаю сейчас».",
                 "Día 6 — planes y ahora."),
        },
    },
    12: {
        "grammar_sections": _gs(
            [
                {"title": "Прошедшее (pretérito)", "text": "Действие завершено в прошлом: ayer, anoche. «Вчера я сделал»."},
                {"title": "Правильные -AR", "text": "hablé, hablaste, habló, hablamos, hablaron. Окончания: -é, -aste, -ó, -amos, -aron."},
                {"title": "Правильные -ER/-IR", "text": "comí, comiste, comió, comimos, comieron. Окончания: -í, -iste, -ió, -imos, -ieron."},
                {"title": "Неправильный ir/ser", "text": "fui = я пошёл / я был. Fuiste, fue. Одинаково для ir и ser."},
                {"title": "Маркеры времени", "text": "ayer (вчера), anoche (вчера ночью), el fin de semana, la semana pasada."},
            ],
            [
                {"title": "Preterite", "text": "Completed past actions: ayer, anoche."},
                {"title": "Regular -AR", "text": "hablé, hablaste, habló…"},
                {"title": "Regular -ER/-IR", "text": "comí, comiste, comió…"},
                {"title": "ir/ser → fui", "text": "fui = I went / I was."},
                {"title": "Time markers", "text": "ayer, anoche, el fin de semana."},
            ],
            [
                {"title": "Pretérito", "text": "Acción terminada: ayer."},
                {"title": "-AR", "text": "hablé, hablaste…"},
                {"title": "-ER/-IR", "text": "comí, comiste…"},
                {"title": "fui", "text": "fui, fuiste, fue."},
                {"title": "Marcadores", "text": "ayer, anoche."},
            ],
        ),
        "examples": [
            _ex("Ayer comí tacos.", "Yesterday I ate tacos.", "Вчера я ел тако."),
            _ex("Anoche fui al cine.", "Last night I went to the cinema.", "Вчера ночью ходил в кино."),
            _ex("¿Qué hiciste ayer?", "What did you do yesterday?", "Что ты делал вчера?"),
            _ex("Hablé con mi mamá.", "I spoke with my mom.", "Я говорил с мамой."),
            _ex("El fin de semana descansé.", "I rested on the weekend.", "На выходных отдыхал."),
            _ex("Fui a la escuela.", "I went to school.", "Я ходил в школу."),
        ],
        "day_focus": {
            1: t("Day 1 — time words: ayer, anoche.",
                 "День 1 — слова времени: ayer, anoche.",
                 "Día 1 — ayer, anoche."),
            2: t("Day 2 — regular -AR past: hablé, hablaste.",
                 "День 2 — прошедшее -AR.",
                 "Día 2 — pretérito -AR."),
            3: t("Day 3 — regular -ER/-IR past: comí, viví.",
                 "День 3 — прошедшее -ER/-IR.",
                 "Día 3 — pretérito -ER/-IR."),
            4: t("Day 4 — fui, fuiste, fue (went/was).",
                 "День 4 — fui, fuiste, fue.",
                 "Día 4 — fui, fue."),
            5: t("Day 5 — tell what you did yesterday.",
                 "День 5 — расскажите, что делали вчера.",
                 "Día 5 — qué hiciste ayer."),
            6: t("Day 6 — full past-tense mini-story.",
                 "День 6 — мини-рассказ в прошедшем времени.",
                 "Día 6 — mini-historia en pasado."),
        },
    },
    13: {
        "grammar_sections": _gs(
            [
                {"title": "Ближайшее будущее (повтор)", "text": "voy a viajar, vas a comer — планы на завтра/скоро."},
                {"title": "Простое будущее", "text": "К инфинитиву: hablaré, comeré, viviré. Mañana hablaré español."},
                {"title": "Вопросительные слова", "text": "¿qué?, ¿dónde?, ¿cuándo?, ¿cómo?, ¿por qué? — основа любого разговора."},
                {"title": "Потому что", "text": "porque — ответ на ¿por qué? No voy porque estoy cansado."},
                {"title": "Финиш A1", "text": "Вы прошли A1! Приветствие, еда, семья, глаголы, время, описание, прошлое и будущее — всё вместе."},
            ],
            [
                {"title": "Near future review", "text": "voy a + infinitive."},
                {"title": "Simple future", "text": "hablaré, comeré, viviré."},
                {"title": "Question words", "text": "qué, dónde, cuándo, cómo, por qué."},
                {"title": "porque", "text": "because — answers ¿por qué?"},
                {"title": "A1 complete!", "text": "You can survive a full day in Mexico."},
            ],
            [
                {"title": "Futuro próximo", "text": "voy a + infinitivo."},
                {"title": "Futuro simple", "text": "hablaré, comeré."},
                {"title": "Interrogativas", "text": "qué, dónde, cuándo."},
                {"title": "porque", "text": "respuesta a ¿por qué?"},
                {"title": "¡A1 completo!", "text": "¡Felicidades!"},
            ],
        ),
        "examples": [
            _ex("Mañana voy a viajar a México.", "Tomorrow I'm going to travel to Mexico.", "Завтра поеду в Мексику."),
            _ex("Algún día hablaré muy bien.", "Someday I'll speak very well.", "Когда-нибудь буду говорить отлично."),
            _ex("¿Qué vas a hacer mañana?", "What will you do tomorrow?", "Что будешь делать завтра?"),
            _ex("¿Por qué estudias español?", "Why do you study Spanish?", "Почему ты учишь испанский?"),
            _ex("Porque me gusta México.", "Because I like Mexico.", "Потому что мне нравится Мексика."),
            _ex("¡Felicidades, terminaste A1!", "Congrats, you finished A1!", "Поздравляем, A1 пройден!"),
        ],
        "day_focus": {
            1: t("Day 1 — question words: qué, dónde, cuándo.",
                 "День 1 — вопросительные слова.",
                 "Día 1 — interrogativas."),
            2: t("Day 2 — voy a… plans for tomorrow.",
                 "День 2 — планы на завтра: voy a…",
                 "Día 2 — voy a mañana."),
            3: t("Day 3 — simple future: hablaré, comeré.",
                 "День 3 — простое будущее.",
                 "Día 3 — futuro simple."),
            4: t("Day 4 — ¿por qué? / porque.",
                 "День 4 — почему / потому что.",
                 "Día 4 — ¿por qué? / porque."),
            5: t("Day 5 — review ser/estar, present, past.",
                 "День 5 — повтор ser/estar, настоящее, прошлое.",
                 "Día 5 — repaso general."),
            6: t("Day 6 — A1 graduation! You can handle a full day in Mexico. ¡Órale!",
                 "День 6 — выпускной A1! Вы справитесь с целым днём в Мексике. ¡Órale!",
                 "Día 6 — ¡graduación A1! ¡Órale!"),
        },
    },
}


def enrich_a1_theory(th: dict, week_num: int, day_in_week: int, new_vocab: list, taught_tokens: set, week_meta: dict, listen_fn) -> None:
    """Apply A1 enrichment to a theory dict in place."""
    pack = A1_THEORY.get(week_num)
    if not pack:
        return

    if pack.get("grammar_sections"):
        th["grammar_sections"] = pack["grammar_sections"]
        # Flat list fallback for older clients
        th["grammar_points"] = {
            lang: [f"{s['title']}: {s['text']}" if s.get("title") else s["text"] for s in sections]
            for lang, sections in pack["grammar_sections"].items()
        }

    day_focus = pack.get("day_focus", {}).get(day_in_week)
    if day_focus:
        word_list = ", ".join(v["es"] for v in new_vocab[:5])
        if len(new_vocab) > 5:
            word_list += "…"
        th["day_focus"] = t(
            f"{day_focus['en']} Today's words: {word_list}.",
            f"{day_focus['ru']} Слова сегодня: {word_list}.",
            f"{day_focus['es']} Palabras de hoy: {word_list}.",
        )

    base_examples = pack.get("examples", []) + th.get("examples", [])
    seen = set()
    merged = []
    for ex in base_examples:
        es = ex.get("es", "").strip()
        if es and es not in seen:
            seen.add(es)
            merged.append(ex)
    th["examples"] = listen_fn(week_meta, new_vocab, taught_tokens, merged, limit=6)
