"""52-week / 365-day Mexican Spanish program.

Each WEEK has a theme, an icon, a CEFR level, rich THEORY (a clear lesson on the
topic + grammar with examples), and a vocabulary bank. `builder.py` turns every
week into 6 daily lessons + 1 weekly exam, spacing vocabulary and reusing words
that were already learned (spiral review). Weeks that are not authored in detail
yet are auto-generated as review weeks so the full 365-day calendar always works.

Vocab item format:  (spanish, english, russian).
"""


def t(en, ru, es):
    return {"en": en, "ru": ru, "es": es}


def theory(intro_en, intro_ru, intro_es,
           gram_en, gram_ru, gram_es,
           examples, tip_en, tip_ru, tip_es):
    """A structured theory block shown before the week's exercises."""
    return {
        "intro": t(intro_en, intro_ru, intro_es),
        "grammar": t(gram_en, gram_ru, gram_es),
        "examples": [{"es": e[0], "en": e[1], "ru": e[2]} for e in examples],
        "tip": t(tip_en, tip_ru, tip_es),
    }


def WK(week, level, icon, theme_en, theme_ru, theme_es, th, vocab, chunks=None):
    """chunks: list of (template_with_'___', answer, english, russian) for cloze exercises."""
    return {
        "week": week, "level": level, "icon": icon,
        "theme": t(theme_en, theme_ru, theme_es),
        "theory": th, "vocab": vocab,
        "chunks": [
            {"template": c[0], "answer": c[1], "en": c[2], "ru": c[3]} for c in (chunks or [])
        ],
    }


WEEKS = [
    # ==================== A1 (weeks 1-13, ~3 months) ====================
    WK(1, "A1", "👋", "Greetings & Pronouns", "Приветствия и местоимения", "Saludos y pronombres",
       theory(
           "This week you start speaking! You'll greet people, introduce yourself and meet the subject pronouns (I, you, he...).",
           "На этой неделе вы начинаете говорить! Приветствия, знакомство и личные местоимения (я, ты, он...).",
           "¡Esta semana empiezas a hablar! Saludos, presentaciones y los pronombres personales.",
           "Subject pronouns: yo (I), tú (you), él/ella (he/she), nosotros (we), ustedes (you all), ellos (they). In Mexico 'ustedes' is used for ALL plural 'you' (there is no 'vosotros').",
           "Местоимения: yo (я), tú (ты), él/ella (он/она), nosotros (мы), ustedes (вы), ellos (они). В Мексике 'ustedes' — для любого «вы» во мн. числе (нет 'vosotros').",
           "Pronombres: yo, tú, él/ella, nosotros, ustedes, ellos. En México 'ustedes' se usa para todo plural (no hay 'vosotros').",
           [("Yo me llamo Ana.", "My name is Ana.", "Меня зовут Ана."),
            ("¿Cómo estás tú?", "How are you?", "Как ты?"),
            ("Él es mi amigo.", "He is my friend.", "Он мой друг.")],
           "'¿Qué onda?' is a super common casual 'What's up?' in Mexico.",
           "«¿Qué onda?» — очень частое неформальное «как дела?» в Мексике.",
           "'¿Qué onda?' es un saludo casual muy mexicano."),
       [("Hola", "Hello", "Привет"), ("Buenos días", "Good morning", "Доброе утро"),
        ("Buenas tardes", "Good afternoon", "Добрый день"), ("Buenas noches", "Good evening/night", "Добрый вечер"),
        ("Adiós", "Goodbye", "Пока"), ("¿Qué onda?", "What's up? (casual)", "Как дела? (разг.)"),
        ("¿Cómo te llamas?", "What's your name?", "Как тебя зовут?"), ("Me llamo...", "My name is...", "Меня зовут..."),
        ("Mucho gusto", "Nice to meet you", "Приятно познакомиться"), ("¿Cómo estás?", "How are you?", "Как ты?"),
        ("Estoy bien", "I'm fine", "Я в порядке"), ("¿Y tú?", "And you?", "А ты?"),
        ("yo", "I", "я"), ("tú", "you", "ты"), ("él", "he", "он"), ("ella", "she", "она"),
        ("nosotros", "we", "мы"), ("ustedes", "you (plural)", "вы"), ("ellos", "they", "они"),
        ("por favor", "please", "пожалуйста"), ("gracias", "thank you", "спасибо"),
        ("de nada", "you're welcome", "пожалуйста (ответ)"), ("sí", "yes", "да"), ("no", "no", "нет")],
       [("Hola, me ___ Ana.", "llamo", "Hi, my name is Ana.", "Привет, меня зовут Ана."),
        ("Buenos ___.", "días", "Good morning.", "Доброе утро."),
        ("Mucho ___.", "gusto", "Nice to meet you.", "Приятно познакомиться."),
        ("¿Cómo te ___?", "llamas", "What's your name?", "Как тебя зовут?"),
        ("Estoy ___, gracias.", "bien", "I'm fine, thanks.", "Я в порядке, спасибо."),
        ("¿Cómo ___ tú?", "estás", "How are you?", "Как ты?")]),

    WK(2, "A1", "🔢", "Numbers & Nouns", "Числа и существительные", "Números y sustantivos",
       theory(
           "Learn to count and meet grammatical gender: every noun is masculine (el) or feminine (la).",
           "Учимся считать и узнаём грамматический род: каждое существительное мужского (el) или женского (la) рода.",
           "Aprende a contar y conoce el género: cada sustantivo es masculino (el) o femenino (la).",
           "Nouns ending in -o are usually masculine (el libro); those ending in -a usually feminine (la casa). Plurals add -s/-es: el libro → los libros.",
           "Слова на -o обычно мужского рода (el libro), на -a — женского (la casa). Мн. число: +-s/-es: el libro → los libros.",
           "Los sustantivos en -o suelen ser masculinos (el libro); en -a, femeninos (la casa). Plural: +-s/-es.",
           [("el libro", "the book (m)", "книга"), ("la casa", "the house (f)", "дом"),
            ("los libros", "the books", "книги"), ("dos tacos", "two tacos", "два тако")],
           "Numbers 16-29 are written as one word: dieciséis, veintiuno.",
           "Числа 16-29 пишутся одним словом: dieciséis, veintiuno.",
           "Los números 16-29 se escriben juntos: dieciséis, veintiuno."),
       [("uno", "one", "один"), ("dos", "two", "два"), ("tres", "three", "три"), ("cuatro", "four", "четыре"),
        ("cinco", "five", "пять"), ("seis", "six", "шесть"), ("siete", "seven", "семь"), ("ocho", "eight", "восемь"),
        ("nueve", "nine", "девять"), ("diez", "ten", "десять"), ("once", "eleven", "одиннадцать"),
        ("doce", "twelve", "двенадцать"), ("trece", "thirteen", "тринадцать"), ("catorce", "fourteen", "четырнадцать"),
        ("quince", "fifteen", "пятнадцать"), ("veinte", "twenty", "двадцать"), ("treinta", "thirty", "тридцать"),
        ("cien", "one hundred", "сто"), ("el libro", "book", "книга"), ("la casa", "house", "дом"),
        ("el", "the (m)", "определённый артикль м.р."), ("la", "the (f)", "определённый артикль ж.р."),
        ("los", "the (m pl)", "the мн. м.р."), ("las", "the (f pl)", "the мн. ж.р.")],
       [("Tengo ___ tacos.", "dos", "I have two tacos.", "У меня два тако."),
        ("___ casa es grande.", "La", "The house is big.", "Дом большой."),
        ("Quiero ___ libro.", "el", "I want the book.", "Я хочу книгу."),
        ("Cinco más cinco son ___.", "diez", "Five plus five is ten.", "Пять плюс пять — десять."),
        ("___ libros son nuevos.", "Los", "The books are new.", "Книги новые."),
        ("Tengo ___ años.", "veinte", "I'm twenty years old.", "Мне двадцать лет.")]),

    WK(3, "A1", "⭐", "Ser vs Estar", "Ser и Estar", "Ser y Estar",
       theory(
           "Spanish has TWO verbs for 'to be'. This is key! 'Ser' for identity/permanent things, 'estar' for location/feelings.",
           "В испанском ДВА глагола «быть». Это важно! «Ser» — для постоянного/сущности, «estar» — для места/состояния.",
           "El español tiene DOS verbos 'to be'. 'Ser' para identidad; 'estar' para lugar y estado.",
           "SER: soy, eres, es, somos, son (jobs, origin, traits). ESTAR: estoy, estás, está, estamos, están (location, mood).",
           "SER: soy, eres, es, somos, son (профессия, происхождение, качества). ESTAR: estoy, estás, está, estamos, están (место, настроение).",
           "SER: soy, eres, es, somos, son. ESTAR: estoy, estás, está, estamos, están.",
           [("Yo soy de México.", "I am from Mexico.", "Я из Мексики."),
            ("Ella está cansada.", "She is tired.", "Она устала."),
            ("Estamos en casa.", "We are at home.", "Мы дома.")],
           "Rule of thumb: if it can change soon (mood, place) → estar; if it defines you → ser.",
           "Правило: если может скоро измениться (настроение, место) → estar; если определяет вас → ser.",
           "Regla: si puede cambiar pronto → estar; si te define → ser."),
       [("soy", "I am (ser)", "я есть"), ("eres", "you are", "ты есть"), ("es", "he/she is", "он/она есть"),
        ("somos", "we are", "мы есть"), ("son", "they are", "они есть"),
        ("estoy", "I am (estar)", "я нахожусь"), ("estás", "you are", "ты находишься"), ("está", "he/she is", "он/она находится"),
        ("estamos", "we are", "мы находимся"), ("están", "they are", "они находятся"),
        ("aquí", "here", "здесь"), ("allá", "there", "там"), ("cansado", "tired", "уставший"),
        ("feliz", "happy", "счастливый"), ("de México", "from Mexico", "из Мексики"),
        ("¿quién?", "who?", "кто?"), ("¿dónde?", "where?", "где?"), ("amigo", "friend (m)", "друг"),
        ("amiga", "friend (f)", "подруга"), ("bien", "well/fine", "хорошо"), ("mal", "bad(ly)", "плохо"),
        ("muy", "very", "очень"), ("también", "also", "тоже"), ("pero", "but", "но")],
       [("Yo ___ de México.", "soy", "I am from Mexico.", "Я из Мексики."),
        ("Ella ___ cansada.", "está", "She is tired.", "Она устала."),
        ("Nosotros ___ en casa.", "estamos", "We are at home.", "Мы дома."),
        ("Él ___ mi amigo.", "es", "He is my friend.", "Он мой друг."),
        ("Yo ___ bien, gracias.", "estoy", "I'm well, thanks.", "Я в порядке, спасибо."),
        ("Ellos ___ estudiantes.", "son", "They are students.", "Они студенты.")]),

    WK(4, "A1", "👨‍👩‍👧", "Family & Possessives", "Семья и притяжательные", "Familia y posesivos",
       theory(
           "Talk about your family and say what belongs to whom using possessive adjectives.",
           "Говорим о семье и о принадлежности с помощью притяжательных прилагательных.",
           "Habla de tu familia y de lo que es de cada quien con los posesivos.",
           "Possessives: mi (my), tu (your), su (his/her/your-formal), nuestro (our). They agree in number: mis hermanos.",
           "Притяжательные: mi (мой), tu (твой), su (его/её/Ваш), nuestro (наш). Согласуются в числе: mis hermanos.",
           "Posesivos: mi, tu, su, nuestro. Concuerdan en número: mis hermanos.",
           [("mi mamá", "my mom", "моя мама"), ("tus hermanos", "your siblings", "твои братья/сёстры"),
            ("nuestra casa", "our house", "наш дом")],
           "Mexicans often add cariño (affection): 'mi'jo' = mijo = my son (a warm word).",
           "Мексиканцы часто говорят ласково: «mijo» — сынок (тёплое слово).",
           "En México se usa 'mijo/mija' con cariño para hijo/hija."),
       [("la mamá", "mom", "мама"), ("el papá", "dad", "папа"), ("el hermano", "brother", "брат"),
        ("la hermana", "sister", "сестра"), ("el hijo", "son", "сын"), ("la hija", "daughter", "дочь"),
        ("el abuelo", "grandfather", "дедушка"), ("la abuela", "grandmother", "бабушка"),
        ("el tío", "uncle", "дядя"), ("la tía", "aunt", "тётя"), ("el esposo", "husband", "муж"),
        ("la esposa", "wife", "жена"), ("los padres", "parents", "родители"), ("el bebé", "baby", "малыш"),
        ("mi", "my", "мой"), ("tu", "your", "твой"), ("su", "his/her/your", "его/её/Ваш"),
        ("nuestro", "our", "наш"), ("la familia", "family", "семья"), ("el niño", "boy", "мальчик"),
        ("la niña", "girl", "девочка"), ("grande", "big", "большой"), ("pequeño", "small", "маленький")],
       [("___ mamá se llama Rosa.", "Mi", "My mom's name is Rosa.", "Мою маму зовут Роса."),
        ("¿Cómo se llama ___ hermano?", "tu", "What's your brother's name?", "Как зовут твоего брата?"),
        ("___ casa es bonita.", "Nuestra", "Our house is pretty.", "Наш дом красивый."),
        ("Tengo dos ___.", "hermanos", "I have two siblings.", "У меня двое братьев/сестёр."),
        ("El hermano de mi mamá es mi ___.", "tío", "My mom's brother is my uncle.", "Брат моей мамы — мой дядя."),
        ("La mamá de mi mamá es mi ___.", "abuela", "My mom's mom is my grandma.", "Мама моей мамы — моя бабушка.")]),

    WK(5, "A1", "🌮", "Food & 'Me gusta'", "Еда и «Me gusta»", "Comida y 'Me gusta'",
       theory(
           "Order Mexican food and say what you like with 'me gusta'.",
           "Заказываем мексиканскую еду и говорим, что нравится, через «me gusta».",
           "Pide comida mexicana y di qué te gusta con 'me gusta'.",
           "'Me gusta' + singular/verb; 'me gustan' + plural. Add articles: quiero UN taco, LA salsa.",
           "«Me gusta» + ед.ч./глагол; «me gustan» + мн.ч. Артикли: quiero UN taco, LA salsa.",
           "'Me gusta' + singular; 'me gustan' + plural. Artículos: un taco, la salsa.",
           [("Me gusta el taco.", "I like the taco.", "Мне нравится тако."),
            ("Me gustan los tacos.", "I like tacos.", "Мне нравятся тако."),
            ("Quiero un café, por favor.", "I want a coffee, please.", "Я хочу кофе, пожалуйста.")],
           "'¿Con todo?' at a taquería = with onion & cilantro.",
           "«¿Con todo?» в такерии — с луком и кинзой.",
           "'¿Con todo?' = con cebolla y cilantro."),
       [("el taco", "taco", "тако"), ("la tortilla", "tortilla", "тортилья"), ("la salsa", "salsa/sauce", "соус"),
        ("picante", "spicy", "острый"), ("el limón", "lime", "лайм"), ("el agua", "water", "вода"),
        ("el café", "coffee", "кофе"), ("la leche", "milk", "молоко"), ("el jugo", "juice", "сок"),
        ("la fruta", "fruit", "фрукты"), ("la verdura", "vegetable", "овощи"), ("el pollo", "chicken", "курица"),
        ("me gusta", "I like", "мне нравится"), ("me gustan", "I like (pl)", "мне нравятся"),
        ("quiero", "I want", "я хочу"), ("un", "a (m)", "один/артикль м.р."), ("una", "a (f)", "одна/артикль ж.р."),
        ("¿cuánto cuesta?", "how much?", "сколько стоит?"), ("la cuenta", "the bill", "счёт"),
        ("delicioso", "delicious", "вкусный"), ("tengo hambre", "I'm hungry", "я голоден"),
        ("tengo sed", "I'm thirsty", "я хочу пить"), ("rico", "tasty", "вкусный")],
       [("Me ___ los tacos.", "gustan", "I like tacos.", "Мне нравятся тако."),
        ("Me ___ el café.", "gusta", "I like coffee.", "Мне нравится кофе."),
        ("___ un taco, por favor.", "Quiero", "I want a taco, please.", "Я хочу тако, пожалуйста."),
        ("La ___ está muy picante.", "salsa", "The salsa is very spicy.", "Соус очень острый."),
        ("Tengo ___, quiero agua.", "sed", "I'm thirsty, I want water.", "Я хочу пить, хочу воды."),
        ("¿Cuánto ___ la cuenta?", "cuesta", "How much is the bill?", "Сколько стоит счёт?")]),

    WK(6, "A1", "🗣️", "Present tense: -AR verbs", "Настоящее: глаголы -AR", "Presente: verbos -AR",
       theory(
           "Most Spanish verbs end in -ar. Learn to conjugate them — this unlocks hundreds of verbs!",
           "Большинство глаголов на -ar. Учимся спрягать — это открывает сотни глаголов!",
           "La mayoría de verbos terminan en -ar. ¡Conjúgalos y desbloquea cientos!",
           "hablar → hablo, hablas, habla, hablamos, hablan. Remove -ar, add: -o, -as, -a, -amos, -an.",
           "hablar → hablo, hablas, habla, hablamos, hablan. Убираем -ar, добавляем: -o, -as, -a, -amos, -an.",
           "hablar → hablo, hablas, habla, hablamos, hablan.",
           [("Yo hablo español.", "I speak Spanish.", "Я говорю по-испански."),
            ("Ella trabaja aquí.", "She works here.", "Она работает здесь."),
            ("Nosotros estudiamos.", "We study.", "Мы учимся.")],
           "You can drop the pronoun: 'hablo' already means 'I speak'.",
           "Местоимение можно опускать: «hablo» уже значит «я говорю».",
           "Puedes omitir el pronombre: 'hablo' ya es 'yo hablo'."),
       [("hablar", "to speak", "говорить"), ("hablo", "I speak", "я говорю"), ("hablas", "you speak", "ты говоришь"),
        ("habla", "he/she speaks", "он/она говорит"), ("hablamos", "we speak", "мы говорим"),
        ("trabajar", "to work", "работать"), ("trabajo", "I work", "я работаю"),
        ("estudiar", "to study", "учиться"), ("estudio", "I study", "я учусь"),
        ("caminar", "to walk", "ходить"), ("cocinar", "to cook", "готовить"), ("comprar", "to buy", "покупать"),
        ("escuchar", "to listen", "слушать"), ("cantar", "to sing", "петь"), ("bailar", "to dance", "танцевать"),
        ("mirar", "to watch/look", "смотреть"), ("descansar", "to rest", "отдыхать"),
        ("el español", "Spanish (lang.)", "испанский"), ("mucho", "a lot", "много"),
        ("poco", "a little", "мало"), ("ahora", "now", "сейчас"), ("siempre", "always", "всегда"),
        ("nunca", "never", "никогда")],
       [("Yo ___ español.", "hablo", "I speak Spanish.", "Я говорю по-испански."),
        ("Ella ___ aquí.", "trabaja", "She works here.", "Она работает здесь."),
        ("Nosotros ___ mucho.", "estudiamos", "We study a lot.", "Мы много учимся."),
        ("Yo no ___ inglés.", "hablo", "I don't speak English.", "Я не говорю по-английски."),
        ("Me gusta ___ música.", "escuchar", "I like to listen to music.", "Мне нравится слушать музыку."),
        ("Yo ___ en casa.", "cocino", "I cook at home.", "Я готовлю дома.")]),

    WK(7, "A1", "📖", "Present tense: -ER / -IR verbs", "Настоящее: -ER / -IR", "Presente: -ER / -IR",
       theory(
           "The other two verb families: -er and -ir. Very similar endings.",
           "Ещё две группы глаголов: -er и -ir. Очень похожие окончания.",
           "Las otras dos familias: -er e -ir. Terminaciones muy parecidas.",
           "comer → como, comes, come, comemos, comen. vivir → vivo, vives, vive, vivimos, viven.",
           "comer → como, comes, come, comemos, comen. vivir → vivo, vives, vive, vivimos, viven.",
           "comer → como, comes, come, comemos, comen. vivir → vivo, vives, vive, vivimos, viven.",
           [("Como tacos.", "I eat tacos.", "Я ем тако."),
            ("¿Dónde vives?", "Where do you live?", "Где ты живёшь?"),
            ("Ella lee un libro.", "She reads a book.", "Она читает книгу.")],
           "-er and -ir differ only in 'we': comEmos vs vivImos.",
           "-er и -ir отличаются только в «мы»: comEmos vs vivImos.",
           "-er e -ir difieren solo en 'nosotros': comemos vs vivimos."),
       [("comer", "to eat", "есть"), ("como", "I eat", "я ем"), ("comes", "you eat", "ты ешь"),
        ("come", "he/she eats", "он/она ест"), ("beber", "to drink", "пить"), ("bebo", "I drink", "я пью"),
        ("leer", "to read", "читать"), ("leo", "I read", "я читаю"), ("aprender", "to learn", "учиться"),
        ("vivir", "to live", "жить"), ("vivo", "I live", "я живу"), ("vives", "you live", "ты живёшь"),
        ("escribir", "to write", "писать"), ("escribo", "I write", "я пишу"),
        ("abrir", "to open", "открывать"), ("correr", "to run", "бегать"),
        ("ver", "to see", "видеть"), ("veo", "I see", "я вижу"),
        ("el libro", "book", "книга"), ("la carta", "letter", "письмо"),
        ("¿dónde?", "where?", "где?"), ("¿qué?", "what?", "что?"), ("con", "with", "с"), ("sin", "without", "без")],
       [("Yo ___ tacos.", "como", "I eat tacos.", "Я ем тако."),
        ("¿Dónde ___ tú?", "vives", "Where do you live?", "Где ты живёшь?"),
        ("Ella ___ un libro.", "lee", "She reads a book.", "Она читает книгу."),
        ("Yo ___ en México.", "vivo", "I live in Mexico.", "Я живу в Мексике."),
        ("Yo ___ una carta.", "escribo", "I write a letter.", "Я пишу письмо."),
        ("Nosotros ___ español.", "aprendemos", "We learn Spanish.", "Мы учим испанский.")]),

    WK(8, "A1", "📅", "Time, Days & Months", "Время, дни и месяцы", "Tiempo, días y meses",
       theory(
           "Tell time, name the days and months, and talk about your schedule.",
           "Учимся называть время, дни недели и месяцы, говорить о расписании.",
           "Di la hora, los días y los meses, y habla de tu horario.",
           "Time: 'Es la una' (1:00), 'Son las dos' (2:00). Days/months are lowercase. Dates: 'el 5 de mayo'.",
           "Время: «Es la una» (1:00), «Son las dos» (2:00). Дни/месяцы — с маленькой буквы. Даты: «el 5 de mayo».",
           "Hora: 'Es la una', 'Son las dos'. Días/meses en minúscula. Fecha: 'el 5 de mayo'.",
           [("¿Qué hora es?", "What time is it?", "Который час?"),
            ("Son las tres.", "It's three o'clock.", "Три часа."),
            ("Hoy es lunes.", "Today is Monday.", "Сегодня понедельник.")],
           "'ahorita' famously means 'right now'... or maybe later. Very Mexican!",
           "«ahorita» знаменито значит «прямо сейчас»... или потом. Очень по-мексикански!",
           "'ahorita' = ahora mismo... o quizá después."),
       [("lunes", "Monday", "понедельник"), ("martes", "Tuesday", "вторник"), ("miércoles", "Wednesday", "среда"),
        ("jueves", "Thursday", "четверг"), ("viernes", "Friday", "пятница"), ("sábado", "Saturday", "суббота"),
        ("domingo", "Sunday", "воскресенье"), ("hoy", "today", "сегодня"), ("mañana", "tomorrow", "завтра"),
        ("ayer", "yesterday", "вчера"), ("la hora", "hour/time", "час/время"), ("¿qué hora es?", "what time is it?", "который час?"),
        ("la mañana", "morning", "утро"), ("la tarde", "afternoon", "день/вечер"), ("la noche", "night", "ночь"),
        ("ahorita", "right now (Mex.)", "прямо сейчас"), ("enero", "January", "январь"), ("febrero", "February", "февраль"),
        ("marzo", "March", "март"), ("abril", "April", "апрель"), ("mayo", "May", "май"),
        ("el día", "day", "день"), ("la semana", "week", "неделя"), ("el mes", "month", "месяц")],
       [("¿Qué ___ es?", "hora", "What time is it?", "Который час?"),
        ("Son las ___.", "tres", "It's three o'clock.", "Три часа."),
        ("___ es lunes.", "Hoy", "Today is Monday.", "Сегодня понедельник."),
        ("Mañana es ___.", "martes", "Tomorrow is Tuesday.", "Завтра вторник."),
        ("Mi cumpleaños es en ___.", "mayo", "My birthday is in May.", "Мой день рождения в мае."),
        ("Nos vemos en la ___.", "tarde", "See you in the afternoon.", "Увидимся днём.")]),

    WK(9, "A1", "🎨", "Describing Things", "Описание вещей", "Describir cosas",
       theory(
           "Use adjectives and colors. In Spanish, adjectives usually go AFTER the noun and agree with it.",
           "Прилагательные и цвета. В испанском прилагательное обычно ПОСЛЕ существительного и согласуется с ним.",
           "Usa adjetivos y colores. En español el adjetivo va DESPUÉS del sustantivo y concuerda.",
           "Agreement: casa roja (f), coche rojo (m), casas rojas (f pl). Adjective follows the noun: 'un gato negro'.",
           "Согласование: casa roja (ж), coche rojo (м), casas rojas (мн). Прилагательное после слова: «un gato negro».",
           "Concordancia: casa roja, coche rojo, casas rojas. El adjetivo va después: 'un gato negro'.",
           [("un coche rojo", "a red car", "красная машина"),
            ("una casa grande", "a big house", "большой дом"),
            ("los libros nuevos", "the new books", "новые книги")],
           "'padre' and 'chido' both mean 'cool/awesome' in Mexico.",
           "«padre» и «chido» — оба значат «классно» в Мексике.",
           "'padre' y 'chido' significan 'genial' en México."),
       [("rojo", "red", "красный"), ("azul", "blue", "синий"), ("verde", "green", "зелёный"),
        ("amarillo", "yellow", "жёлтый"), ("negro", "black", "чёрный"), ("blanco", "white", "белый"),
        ("bueno", "good", "хороший"), ("malo", "bad", "плохой"), ("nuevo", "new", "новый"),
        ("viejo", "old", "старый"), ("bonito", "pretty", "красивый"), ("feo", "ugly", "уродливый"),
        ("alto", "tall", "высокий"), ("bajo", "short", "низкий"), ("largo", "long", "длинный"),
        ("corto", "short (length)", "короткий"), ("caro", "expensive", "дорогой"), ("barato", "cheap", "дешёвый"),
        ("el coche", "car", "машина"), ("chido", "cool (Mex.)", "круто"), ("padre", "awesome (Mex.)", "классно"),
        ("fácil", "easy", "лёгкий"), ("difícil", "difficult", "трудный"), ("importante", "important", "важный")],
       [("Tengo un coche ___.", "rojo", "I have a red car.", "У меня красная машина."),
        ("Es una casa ___.", "grande", "It's a big house.", "Это большой дом."),
        ("Los tacos están muy ___.", "ricos", "The tacos are very tasty.", "Тако очень вкусные."),
        ("El libro es ___.", "nuevo", "The book is new.", "Книга новая."),
        ("¡Qué ___!", "padre", "How cool!", "Как классно!"),
        ("El español es ___.", "fácil", "Spanish is easy.", "Испанский лёгкий.")]),

    WK(10, "A1", "🤲", "Tener & expressions", "Tener и выражения", "Tener y expresiones",
       theory(
           "'Tener' (to have) is used in many everyday expressions about age, hunger, and more.",
           "«Tener» (иметь) используется во многих выражениях: о возрасте, голоде и др.",
           "'Tener' se usa en muchas expresiones: edad, hambre, etc.",
           "tengo, tienes, tiene, tenemos, tienen. Idioms: tener hambre/sed/frío/calor/sueño; tener X años (age).",
           "tengo, tienes, tiene, tenemos, tienen. Идиомы: tener hambre/sed/frío/calor/sueño; tener X años (возраст).",
           "tengo, tienes, tiene, tenemos, tienen. Modismos: tener hambre/frío; tener X años.",
           [("Tengo 25 años.", "I'm 25 years old.", "Мне 25 лет."),
            ("Tengo frío.", "I'm cold.", "Мне холодно."),
            ("¿Cuántos años tienes?", "How old are you?", "Сколько тебе лет?")],
           "Say age with tener, not ser: 'tengo 30 años' (not soy).",
           "Возраст — через tener, не ser: «tengo 30 años».",
           "La edad con tener: 'tengo 30 años', no 'soy'."),
       [("tener", "to have", "иметь"), ("tengo", "I have", "я имею"), ("tienes", "you have", "ты имеешь"),
        ("tiene", "he/she has", "он/она имеет"), ("tenemos", "we have", "мы имеем"),
        ("tener hambre", "to be hungry", "быть голодным"), ("tener sed", "to be thirsty", "хотеть пить"),
        ("tener frío", "to be cold", "мёрзнуть"), ("tener calor", "to be hot", "быть жарко"),
        ("tener sueño", "to be sleepy", "хотеть спать"), ("tener años", "to be ... years old", "быть ... лет"),
        ("tener razón", "to be right", "быть правым"), ("tener prisa", "to be in a hurry", "спешить"),
        ("¿cuántos?", "how many?", "сколько?"), ("el año", "year", "год"),
        ("joven", "young", "молодой"), ("mayor", "older", "старший"), ("el trabajo", "job/work", "работа"),
        ("el dinero", "money", "деньги"), ("el tiempo", "time/weather", "время/погода"),
        ("mucho", "much", "много"), ("todo", "all", "всё"), ("nada", "nothing", "ничего")],
       [("Yo ___ 25 años.", "tengo", "I'm 25 years old.", "Мне 25 лет."),
        ("¿Cuántos años ___?", "tienes", "How old are you?", "Сколько тебе лет?"),
        ("Tengo ___, quiero comer.", "hambre", "I'm hungry, I want to eat.", "Я голоден, хочу есть."),
        ("Ella ___ frío.", "tiene", "She is cold.", "Ей холодно."),
        ("Tengo ___, quiero dormir.", "sueño", "I'm sleepy, I want to sleep.", "Я хочу спать."),
        ("Nosotros ___ prisa.", "tenemos", "We're in a hurry.", "Мы спешим.")]),

    WK(11, "A1", "🚶", "Ir, Near Future & 'Right Now'", "Ir, будущее и «прямо сейчас»", "Ir, futuro próximo y presente continuo",
       theory(
           "Two power tools this week: talk about what you're GOING to do (near future) and what you're doing RIGHT NOW (present continuous).",
           "Два мощных инструмента: говорим, что СОБИРАЕМСЯ делать (ближайшее будущее) и что делаем ПРЯМО СЕЙЧАС (настоящее продолженное).",
           "Dos herramientas: lo que VAS a hacer (futuro próximo) y lo que estás haciendo AHORA (presente continuo).",
           "IR: voy, vas, va, vamos, van. Near future = ir + a + infinitive ('voy a comer'). RIGHT NOW = estar + gerund: -ar→-ando (hablando), -er/-ir→-iendo (comiendo, viviendo). 'a + el' = 'al'.",
           "IR: voy, vas, va, vamos, van. Будущее = ir + a + инфинитив («voy a comer»). СЕЙЧАС = estar + герундий: -ar→-ando (hablando), -er/-ir→-iendo (comiendo). «a + el» = «al».",
           "IR: voy, vas, va, vamos, van. Futuro = ir + a + infinitivo. AHORA = estar + gerundio: -ando / -iendo.",
           [("Voy a estudiar mañana.", "I'm going to study tomorrow.", "Завтра я буду учиться."),
            ("Estoy comiendo tacos.", "I'm eating tacos (right now).", "Я ем тако (сейчас)."),
            ("¿Qué estás haciendo?", "What are you doing?", "Что ты делаешь?")],
           "'Vámonos' = let's go! And '¿Qué estás haciendo?' → 'ahí nomás' = 'just hanging out' in Mexico.",
           "«Vámonos» — пошли! А на «что делаешь?» в Мексике отвечают «ahí nomás» — «да так, ничего».",
           "'Vámonos' = ¡vamos! Y a '¿qué haces?' → 'ahí nomás' en México."),
       [("ir", "to go", "идти"), ("voy", "I go", "я иду"), ("vas", "you go", "ты идёшь"),
        ("va", "he/she goes", "он/она идёт"), ("vamos", "we go/let's go", "идём"), ("van", "they go", "они идут"),
        ("voy a", "I'm going to", "я собираюсь"), ("hablando", "speaking", "говоря"),
        ("comiendo", "eating", "кушая"), ("estudiando", "studying", "учась"),
        ("trabajando", "working", "работая"), ("haciendo", "doing", "делая"),
        ("la calle", "street", "улица"), ("la tienda", "store", "магазин"), ("el mercado", "market", "рынок"),
        ("la escuela", "school", "школа"), ("el parque", "park", "парк"), ("el cine", "cinema", "кино"),
        ("a la derecha", "to the right", "направо"), ("a la izquierda", "to the left", "налево"),
        ("derecho", "straight", "прямо"), ("cerca", "near", "близко"), ("lejos", "far", "далеко"),
        ("el camión", "bus (Mex.)", "автобус")],
       [("___ a estudiar.", "Voy", "I'm going to study.", "Я буду учиться."),
        ("¿___ a comer?", "Vas", "Are you going to eat?", "Ты будешь есть?"),
        ("___ al mercado.", "Vamos", "We're going to the market.", "Идём на рынок."),
        ("Estoy ___ español.", "hablando", "I'm speaking Spanish.", "Я говорю по-испански (сейчас)."),
        ("Ella está ___ tacos.", "comiendo", "She is eating tacos.", "Она ест тако (сейчас)."),
        ("¿Qué estás ___?", "haciendo", "What are you doing?", "Что ты делаешь?")]),

    WK(12, "A1", "📜", "First Steps in the Past", "Первые шаги в прошедшем", "Primeros pasos en pasado",
       theory(
           "Time to talk about YESTERDAY. This is your first taste of the past tense (pretérito) — perfect for telling what you did.",
           "Пора рассказать о ВЧЕРА. Это ваше первое знакомство с прошедшим временем (pretérito) — чтобы говорить, что вы делали.",
           "Hora de hablar de AYER. Tu primer contacto con el pretérito para contar qué hiciste.",
           "Regular preterite. -AR: hablé, hablaste, habló, hablamos, hablaron. -ER/-IR: comí, comiste, comió, comimos, comieron. Very useful irregular: ir/ser → fui, fuiste, fue. Time words: ayer, anoche, el fin de semana.",
           "Правильное прошедшее. -AR: hablé, hablaste, habló... -ER/-IR: comí, comiste, comió... Полезный неправильный: ir/ser → fui, fuiste, fue. Маркеры: ayer, anoche, el fin de semana.",
           "Pretérito regular. -AR: -é, -aste, -ó... -ER/-IR: -í, -iste, -ió... Irregular clave: fui, fuiste, fue. Marcadores: ayer, anoche.",
           [("Ayer comí tacos.", "Yesterday I ate tacos.", "Вчера я ел тако."),
            ("Anoche fui al cine.", "Last night I went to the cinema.", "Вчера ночью я ходил в кино."),
            ("¿Qué hiciste ayer?", "What did you do yesterday?", "Что ты делал вчера?")],
           "Just the intro here — you'll master the past in A2. For now, 'fui' (I went/was) and '-é/-í' endings get you far.",
           "Здесь только введение — прошедшее вы освоите на A2. Пока хватит «fui» и окончаний «-é/-í».",
           "Solo la intro; dominarás el pasado en A2. Por ahora 'fui' y '-é/-í' bastan."),
       [("ayer", "yesterday", "вчера"), ("anoche", "last night", "вчера ночью"),
        ("el fin de semana", "the weekend", "выходные"), ("hablé", "I spoke", "я говорил"),
        ("hablaste", "you spoke", "ты говорил"), ("habló", "he/she spoke", "он/она говорил(а)"),
        ("comí", "I ate", "я ел"), ("comiste", "you ate", "ты ел"), ("comió", "he/she ate", "он/она ел(а)"),
        ("estudié", "I studied", "я учил"), ("trabajé", "I worked", "я работал"),
        ("fui", "I went / I was", "я пошёл / я был"), ("fuiste", "you went/were", "ты пошёл/был"),
        ("fue", "he/she went/was", "он/она пошёл/был"), ("compré", "I bought", "я купил"),
        ("viví", "I lived", "я жил"), ("escribí", "I wrote", "я писал"),
        ("¿qué hiciste?", "what did you do?", "что ты делал?"), ("terminé", "I finished", "я закончил"),
        ("llegué", "I arrived", "я пришёл"), ("pasado", "past/last", "прошлый"),
        ("todo el día", "all day", "весь день"), ("temprano", "early", "рано")],
       [("Ayer ___ tacos.", "comí", "Yesterday I ate tacos.", "Вчера я ел тако."),
        ("Anoche ___ al cine.", "fui", "Last night I went to the cinema.", "Вчера ночью я ходил в кино."),
        ("Ayer ___ con mi mamá.", "hablé", "Yesterday I spoke with my mom.", "Вчера я говорил с мамой."),
        ("¿Qué ___ ayer?", "comiste", "What did you eat yesterday?", "Что ты ел вчера?"),
        ("Ella ___ mucho ayer.", "estudió", "She studied a lot yesterday.", "Она много училась вчера."),
        ("El fin de semana ___ al mercado.", "fui", "On the weekend I went to the market.", "На выходных я ходил на рынок.")]),

    WK(13, "A1", "🏆", "The Future & A1 Finish", "Будущее и финиш A1", "El futuro y meta A1",
       theory(
           "Final week! Learn to talk about the FUTURE and tie together everything from A1: verbs, ser/estar, questions and the past.",
           "Финальная неделя! Учимся говорить о БУДУЩЕМ и связываем всё из A1: глаголы, ser/estar, вопросы и прошедшее.",
           "¡Última semana! Habla del FUTURO y une todo lo de A1: verbos, ser/estar, preguntas y pasado.",
           "Two easy futures: (1) ir + a + infinitive ('voy a viajar' = I'm going to travel); (2) simple future, add to the infinitive: -é, -ás, -á, -emos, -án → hablaré, comeré, viviré. Quick review: question words (qué, dónde, cuándo, cómo, por qué) and 'no' before the verb for negation.",
           "Два простых будущих: (1) ir + a + инфинитив («voy a viajar»); (2) простое будущее — к инфинитиву: -é, -ás, -á... → hablaré, comeré. Повтор: вопросы (qué, dónde, cuándo, cómo, por qué) и «no» перед глаголом.",
           "Dos futuros: (1) ir + a + infinitivo; (2) futuro simple: -é, -ás, -á... → hablaré. Repaso: interrogativas y 'no' antes del verbo.",
           [("Mañana voy a viajar.", "Tomorrow I'm going to travel.", "Завтра я поеду путешествовать."),
            ("Algún día hablaré muy bien.", "Someday I'll speak very well.", "Когда-нибудь я буду говорить очень хорошо."),
            ("¿Qué vas a hacer mañana?", "What are you going to do tomorrow?", "Что будешь делать завтра?")],
           "¡Felicidades! You can now survive a whole day in Mexico — greet, order, ask, and talk about past & future. ¡Órale!",
           "¡Felicidades! Теперь вы проживёте целый день в Мексике — поздороваться, заказать, спросить, рассказать о прошлом и будущем. ¡Órale!",
           "¡Felicidades! Ya sobrevives un día en México: saludar, pedir, preguntar y hablar de pasado y futuro."),
       [("mañana", "tomorrow", "завтра"), ("la próxima semana", "next week", "следующая неделя"),
        ("el próximo año", "next year", "следующий год"), ("algún día", "someday", "когда-нибудь"),
        ("voy a", "I'm going to", "я собираюсь"), ("vas a", "you're going to", "ты собираешься"),
        ("hablaré", "I will speak", "я буду говорить"), ("comeré", "I will eat", "я буду есть"),
        ("viajaré", "I will travel", "я буду путешествовать"), ("viajar", "to travel", "путешествовать"),
        ("¿qué?", "what?", "что?"), ("¿dónde?", "where?", "где?"), ("¿cuándo?", "when?", "когда?"),
        ("¿cómo?", "how?", "как?"), ("¿por qué?", "why?", "почему?"), ("porque", "because", "потому что"),
        ("después", "after/later", "потом"), ("primero", "first", "сначала"),
        ("el plan", "plan", "план"), ("el futuro", "future", "будущее"),
        ("¡órale!", "wow!/let's go! (Mex.)", "ого!/давай!"), ("hasta luego", "see you later", "до встречи")],
       [("Mañana ___ a estudiar.", "voy", "Tomorrow I'm going to study.", "Завтра я буду учиться."),
        ("El próximo año ___ a México.", "viajaré", "Next year I'll travel to Mexico.", "В следующем году поеду в Мексику."),
        ("Mañana ___ tacos.", "comeré", "Tomorrow I'll eat tacos.", "Завтра я поем тако."),
        ("¿Qué ___ a hacer mañana?", "vas", "What are you going to do tomorrow?", "Что будешь делать завтра?"),
        ("Algún día ___ español muy bien.", "hablaré", "Someday I'll speak Spanish very well.", "Когда-нибудь я буду говорить по-испански очень хорошо."),
        ("La próxima ___ voy al mercado.", "semana", "Next week I'll go to the market.", "На следующей неделе пойду на рынок.")]),

    # ==================== A2 (weeks 14-26, ~months 4-6) ====================
    WK(14, "A2", "⏰", "Daily Routine (reflexives)", "Распорядок дня", "Rutina diaria",
       theory(
           "Describe your day with reflexive verbs (actions you do to yourself).",
           "Описываем день возвратными глаголами (действия над собой).",
           "Describe tu día con verbos reflexivos.",
           "Reflexives take 'me/te/se/nos': me levanto, te bañas, se acuesta. Sequence with primero, luego, después.",
           "Возвратные с «me/te/se/nos»: me levanto, te bañas, se acuesta. Порядок: primero, luego, después.",
           "Reflexivos: me/te/se/nos. me levanto, te bañas. Orden: primero, luego, después.",
           [("Me levanto a las siete.", "I get up at seven.", "Я встаю в семь."),
            ("Se acuesta tarde.", "He goes to bed late.", "Он ложится поздно."),
            ("Primero desayuno, luego trabajo.", "First I have breakfast, then I work.", "Сначала завтракаю, потом работаю.")],
           "In Mexico breakfast can be huge — 'almuerzo' is a mid-morning meal.",
           "В Мексике завтрак бывает плотным — «almuerzo» это поздний утренний приём пищи.",
           "En México el 'almuerzo' es una comida de media mañana."),
       [("me levanto", "I get up", "я встаю"), ("me baño", "I shower", "я моюсь"), ("me visto", "I get dressed", "я одеваюсь"),
        ("me lavo", "I wash", "я умываюсь"), ("me acuesto", "I go to bed", "я ложусь"), ("me duermo", "I fall asleep", "я засыпаю"),
        ("me despierto", "I wake up", "я просыпаюсь"), ("desayunar", "to have breakfast", "завтракать"),
        ("el desayuno", "breakfast", "завтрак"), ("la comida", "lunch/meal", "обед"), ("la cena", "dinner", "ужин"),
        ("luego", "then", "потом"), ("después", "after", "после"), ("temprano", "early", "рано"),
        ("tarde", "late", "поздно"), ("todos los días", "every day", "каждый день"),
        ("a veces", "sometimes", "иногда"), ("normalmente", "usually", "обычно"),
        ("el trabajo", "work", "работа"), ("la escuela", "school", "школа"),
        ("descansar", "to rest", "отдыхать"), ("regresar", "to return", "возвращаться")]),

    WK(15, "A2", "🛍️", "Shopping & Money", "Покупки и деньги", "Compras y dinero",
       theory(
           "Shop, ask prices and pay. Learn to compare with 'más/menos ... que'.",
           "Покупки, цены и оплата. Сравнение через «más/menos ... que».",
           "Compra, pregunta precios y paga. Compara con 'más/menos ... que'.",
           "Comparisons: más caro que (more expensive than), menos que (less than), tan ... como (as ... as).",
           "Сравнения: más caro que (дороже чем), menos que (меньше чем), tan ... como (такой же как).",
           "Comparaciones: más ... que, menos ... que, tan ... como.",
           [("Es más barato que el otro.", "It's cheaper than the other.", "Дешевле, чем другой."),
            ("¿Me da un descuento?", "Can you give me a discount?", "Дадите скидку?"),
            ("Voy a pagar con tarjeta.", "I'll pay by card.", "Заплачу картой.")],
           "In markets you can politely bargain; in stores prices are usually fixed.",
           "На рынках можно вежливо торговаться; в магазинах цены обычно фиксированы.",
           "En el mercado puedes regatear; en tiendas el precio es fijo."),
       [("barato", "cheap", "дёшево"), ("caro", "expensive", "дорого"), ("el precio", "price", "цена"),
        ("el dinero", "money", "деньги"), ("la tarjeta", "card", "карта"), ("el efectivo", "cash", "наличные"),
        ("comprar", "to buy", "покупать"), ("vender", "to sell", "продавать"), ("pagar", "to pay", "платить"),
        ("la talla", "size", "размер"), ("probar", "to try on", "примерять"), ("el descuento", "discount", "скидка"),
        ("la oferta", "sale/offer", "распродажа"), ("más", "more", "больше"), ("menos", "less", "меньше"),
        ("que", "than", "чем"), ("tan", "as", "так"), ("como", "as/like", "как"),
        ("la ropa", "clothes", "одежда"), ("los zapatos", "shoes", "обувь"), ("la camisa", "shirt", "рубашка"),
        ("el pantalón", "pants", "брюки"), ("la bolsa", "bag", "сумка")]),

    WK(16, "A2", "🍽️", "At the Restaurant", "В ресторане", "En el restaurante",
       theory(
           "Order a full meal politely using 'quisiera' (I would like) and 'me trae' (could you bring me).",
           "Заказ полного обеда вежливо через «quisiera» (я бы хотел) и «me trae» (принесите мне).",
           "Pide una comida completa con 'quisiera' y 'me trae'.",
           "'quisiera' is a polite 'I would like'. 'me trae...' = could you bring me. 'la propina' (tip) is ~10-15%.",
           "«quisiera» — вежливое «я бы хотел». «me trae...» — принесите. Чаевые «la propina» ~10-15%.",
           "'quisiera' es cortés. 'me trae...' para pedir. La propina es ~10-15%.",
           [("Quisiera la sopa, por favor.", "I would like the soup, please.", "Я бы хотел суп, пожалуйста."),
            ("¿Me trae la cuenta?", "Could you bring the bill?", "Принесёте счёт?"),
            ("Está muy rico.", "It's very tasty.", "Очень вкусно.")],
           "Call the waiter with 'joven' or 'señorita', not by whistling!",
           "Официанта зовут «joven» или «señorita», а не свистом!",
           "Al mesero se le llama 'joven' o 'señorita'."),
       [("el menú", "menu", "меню"), ("el mesero", "waiter (Mex.)", "официант"), ("la entrada", "starter", "закуска"),
        ("el plato fuerte", "main dish", "основное блюдо"), ("el postre", "dessert", "десерт"), ("la propina", "tip", "чаевые"),
        ("la sopa", "soup", "суп"), ("la carne", "meat", "мясо"), ("el pescado", "fish", "рыба"),
        ("el arroz", "rice", "рис"), ("los frijoles", "beans", "фасоль"), ("quisiera", "I would like", "я бы хотел"),
        ("me trae", "bring me", "принесите"), ("dulce", "sweet", "сладкий"), ("salado", "salty", "солёный"),
        ("la mesa", "table", "стол"), ("el vaso", "glass", "стакан"), ("el plato", "plate/dish", "тарелка/блюдо"),
        ("la servilleta", "napkin", "салфетка"), ("caliente", "hot", "горячий"), ("frío", "cold", "холодный"),
        ("para llevar", "to go/takeout", "с собой")]),

    WK(17, "A2", "✈️", "Travel & Transport", "Путешествия и транспорт", "Viajes y transporte",
       theory(
           "Get around the city and country. Learn transport words and how to buy tickets.",
           "Передвигаемся по городу и стране. Транспорт и покупка билетов.",
           "Muévete por la ciudad. Transporte y cómo comprar boletos.",
           "'¿Cómo llego a...?' = how do I get to...? In Mexico the bus is 'el camión'.",
           "«¿Cómo llego a...?» — как добраться до...? В Мексике автобус — «el camión».",
           "'¿Cómo llego a...?' En México el autobús es 'el camión'.",
           [("¿Cómo llego al centro?", "How do I get downtown?", "Как добраться до центра?"),
            ("Un boleto, por favor.", "One ticket, please.", "Один билет, пожалуйста."),
            ("El avión llega a las diez.", "The plane arrives at ten.", "Самолёт прибывает в десять.")],
           "'el centro' is the historic downtown of a Mexican city.",
           "«el centro» — исторический центр мексиканского города.",
           "'el centro' es el corazón histórico de la ciudad."),
       [("el camión", "bus (Mex.)", "автобус"), ("el metro", "subway", "метро"), ("el taxi", "taxi", "такси"),
        ("el coche", "car", "машина"), ("el avión", "airplane", "самолёт"), ("el boleto", "ticket", "билет"),
        ("el aeropuerto", "airport", "аэропорт"), ("el vuelo", "flight", "рейс"), ("la maleta", "suitcase", "чемодан"),
        ("el pasaporte", "passport", "паспорт"), ("llegar", "to arrive", "прибывать"), ("salir", "to leave", "уезжать"),
        ("el centro", "downtown", "центр"), ("la estación", "station", "станция"), ("el viaje", "trip", "поездка"),
        ("viajar", "to travel", "путешествовать"), ("manejar", "to drive (Mex.)", "водить"),
        ("el mapa", "map", "карта"), ("la esquina", "corner", "угол"), ("la cuadra", "block", "квартал"),
        ("¿cómo llego?", "how do I get?", "как добраться?"), ("perdido", "lost", "потерянный")]),

    WK(18, "A2", "🏨", "Hotel & Lodging", "Отель и жильё", "Hotel y hospedaje",
       theory(
           "Book a room and handle hotel situations. Practice formal 'usted' with staff.",
           "Бронируем номер и общаемся в отеле. Практикуем вежливое «usted».",
           "Reserva un cuarto. Practica el 'usted' formal con el personal.",
           "Use 'usted' (formal you) with staff: '¿Tiene una habitación?'. Verb takes the 'él/ella' form.",
           "С персоналом — «usted» (вежливое вы): «¿Tiene una habitación?». Глагол в форме «él/ella».",
           "Con el personal usa 'usted': '¿Tiene una habitación?'.",
           [("¿Tiene una habitación libre?", "Do you have a free room?", "Есть свободный номер?"),
            ("¿A qué hora es el check-out?", "What time is check-out?", "Во сколько выезд?"),
            ("La llave, por favor.", "The key, please.", "Ключ, пожалуйста.")],
           "'ahorita se lo traigo' — 'I'll bring it right away' (Mexican politeness).",
           "«ahorita se lo traigo» — «сейчас принесу» (мексиканская вежливость).",
           "'ahorita se lo traigo' es muy común en servicio."),
       [("el hotel", "hotel", "отель"), ("la habitación", "room", "номер"), ("la llave", "key", "ключ"),
        ("la reservación", "reservation", "бронь"), ("la recepción", "reception", "ресепшн"), ("limpio", "clean", "чистый"),
        ("sucio", "dirty", "грязный"), ("la toalla", "towel", "полотенце"), ("la cama", "bed", "кровать"),
        ("el baño", "bathroom", "ванная"), ("la ducha", "shower", "душ"), ("libre", "free/available", "свободный"),
        ("ocupado", "occupied", "занятый"), ("usted", "you (formal)", "Вы"), ("¿tiene?", "do you have?", "у вас есть?"),
        ("la noche", "night", "ночь"), ("el precio", "price", "цена"), ("incluido", "included", "включено"),
        ("el equipaje", "luggage", "багаж"), ("el piso", "floor", "этаж"), ("el elevador", "elevator (Mex.)", "лифт"),
        ("cómodo", "comfortable", "удобный")]),

    WK(19, "A2", "📜", "The Past (pretérito)", "Прошедшее (pretérito)", "El pasado (pretérito)",
       theory(
           "Talk about finished past actions with the preterite tense.",
           "Говорим о завершённых действиях в прошлом (pretérito).",
           "Habla de acciones pasadas terminadas con el pretérito.",
           "Regular: -ar → -é,-aste,-ó,-amos,-aron; -er/-ir → -í,-iste,-ió,-imos,-ieron. Key irregulars: fui, tuve, hice.",
           "Правильные: -ar → -é,-aste,-ó...; -er/-ir → -í,-iste,-ió... Важные неправильные: fui, tuve, hice.",
           "Regular: hablé, comí. Irregulares clave: fui, tuve, hice.",
           [("Ayer comí tacos.", "Yesterday I ate tacos.", "Вчера я ел тако."),
            ("Fui al mercado.", "I went to the market.", "Я ходил на рынок."),
            ("¿Qué hiciste?", "What did you do?", "Что ты делал?")],
           "'fui' means both 'I went' and 'I was' — context tells you which.",
           "«fui» значит и «я пошёл», и «я был» — по контексту.",
           "'fui' es 'I went' y 'I was'; el contexto lo aclara."),
       [("ayer", "yesterday", "вчера"), ("hablé", "I spoke", "я говорил"), ("comí", "I ate", "я ел"),
        ("viví", "I lived", "я жил"), ("trabajé", "I worked", "я работал"), ("estudié", "I studied", "я учился"),
        ("compré", "I bought", "я купил"), ("fui", "I went/was", "я пошёл/был"), ("tuve", "I had", "я имел"),
        ("hice", "I did/made", "я сделал"), ("dije", "I said", "я сказал"), ("vine", "I came", "я пришёл"),
        ("estuve", "I was", "я был"), ("vi", "I saw", "я видел"), ("la semana pasada", "last week", "на прошлой неделе"),
        ("el año pasado", "last year", "в прошлом году"), ("anoche", "last night", "прошлой ночью"),
        ("después", "afterwards", "потом"), ("entonces", "then", "тогда"), ("de repente", "suddenly", "вдруг"),
        ("¿qué pasó?", "what happened?", "что случилось?"), ("terminar", "to finish", "заканчивать")]),

    WK(20, "A2", "🩺", "Health & the Doctor", "Здоровье и врач", "Salud y el doctor",
       theory(
           "Explain how you feel and understand a doctor. Use 'me duele' for pain.",
           "Объясняем самочувствие и понимаем врача. Боль — через «me duele».",
           "Explica cómo te sientes. El dolor con 'me duele'.",
           "'me duele + la parte' (singular), 'me duelen + partes' (plural). 'me siento mal' = I feel bad.",
           "«me duele + часть» (ед.), «me duelen + части» (мн.). «me siento mal» — мне плохо.",
           "'me duele la cabeza'; 'me duelen los pies'. 'me siento mal'.",
           [("Me duele la cabeza.", "My head hurts.", "У меня болит голова."),
            ("Tengo fiebre.", "I have a fever.", "У меня температура."),
            ("Necesito una medicina.", "I need medicine.", "Мне нужно лекарство.")],
           "'la farmacia' often has a doctor's consult next door in Mexico.",
           "В Мексике при «la farmacia» часто есть кабинет врача рядом.",
           "En México muchas farmacias tienen consultorio médico."),
       [("el dolor", "pain", "боль"), ("me duele", "it hurts me", "у меня болит"), ("la fiebre", "fever", "температура"),
        ("la tos", "cough", "кашель"), ("la gripa", "flu (Mex.)", "грипп/простуда"), ("la medicina", "medicine", "лекарство"),
        ("la farmacia", "pharmacy", "аптека"), ("me siento mal", "I feel bad", "мне плохо"),
        ("me siento bien", "I feel good", "мне хорошо"), ("el doctor", "doctor", "врач"), ("enfermo", "sick", "больной"),
        ("sano", "healthy", "здоровый"), ("la cabeza", "head", "голова"), ("el estómago", "stomach", "живот"),
        ("la garganta", "throat", "горло"), ("el brazo", "arm", "рука"), ("la pierna", "leg", "нога"),
        ("descansar", "to rest", "отдыхать"), ("necesitar", "to need", "нуждаться"), ("el cuerpo", "body", "тело"),
        ("la cita", "appointment", "приём"), ("cuidarse", "to take care", "беречь себя")]),

    WK(21, "A2", "🧑‍🤝‍🧑", "Describing People", "Описание людей", "Describir personas",
       theory(
           "Describe appearance and personality. Combine ser (traits) with physical vocabulary.",
           "Описываем внешность и характер. Сочетаем ser (качества) с лексикой.",
           "Describe apariencia y personalidad con 'ser'.",
           "'es + adjective' for personality/looks; 'tiene + el pelo/los ojos + color' for features.",
           "«es + прилагательное» — характер/вид; «tiene el pelo/los ojos + цвет» — черты.",
           "'es amable'; 'tiene el pelo negro y los ojos cafés'.",
           [("Es muy amable.", "He/she is very kind.", "Он/она очень добрый."),
            ("Tiene el pelo largo.", "He/she has long hair.", "У него/неё длинные волосы."),
            ("Es alto y delgado.", "He is tall and thin.", "Он высокий и худой.")],
           "In Mexico 'moreno/a' warmly describes darker hair or skin.",
           "В Мексике «moreno/a» тепло описывает тёмные волосы/кожу.",
           "'moreno/a' describe piel o cabello oscuro."),
       [("alto", "tall", "высокий"), ("bajo", "short", "низкий"), ("delgado", "thin", "худой"),
        ("gordo", "chubby", "полный"), ("el pelo", "hair", "волосы"), ("los ojos", "eyes", "глаза"),
        ("amable", "kind", "добрый"), ("simpático", "nice", "приятный"), ("inteligente", "smart", "умный"),
        ("trabajador", "hard-working", "трудолюбивый"), ("tímido", "shy", "застенчивый"), ("divertido", "fun", "весёлый"),
        ("serio", "serious", "серьёзный"), ("fuerte", "strong", "сильный"), ("débil", "weak", "слабый"),
        ("guapo", "handsome", "красивый"), ("bonita", "pretty", "красивая"), ("joven", "young", "молодой"),
        ("moreno", "dark-haired (Mex.)", "смуглый/темноволосый"), ("rubio", "blond", "блондин"),
        ("la barba", "beard", "борода"), ("los lentes", "glasses (Mex.)", "очки")]),

    WK(22, "A2", "🎸", "Hobbies & Sports", "Хобби и спорт", "Pasatiempos y deportes",
       theory(
           "Talk about free time. 'Jugar' for sports/games; 'saber' vs 'poder' for abilities.",
           "Говорим о досуге. «Jugar» — игры/спорт; «saber» vs «poder» — умения.",
           "Habla de tu tiempo libre. 'jugar' para deportes; 'saber' vs 'poder'.",
           "'jugar al fútbol'; 'sé nadar' (I know how to swim); 'puedo ir' (I can go). saber = know how; poder = be able.",
           "«jugar al fútbol»; «sé nadar» (умею плавать); «puedo ir» (могу пойти). saber = уметь; poder = мочь.",
           "'jugar al fútbol'; 'sé nadar'; 'puedo ir'. saber = habilidad; poder = posibilidad.",
           [("Sé tocar la guitarra.", "I know how to play guitar.", "Я умею играть на гитаре."),
            ("Juego fútbol los domingos.", "I play soccer on Sundays.", "Играю в футбол по воскресеньям."),
            ("¿Puedes venir?", "Can you come?", "Можешь прийти?")],
           "Fútbol (soccer) and lucha libre (wrestling) are huge in Mexico.",
           "Футбол и lucha libre (реслинг) очень популярны в Мексике.",
           "El fútbol y la lucha libre son enormes en México."),
       [("el deporte", "sport", "спорт"), ("la música", "music", "музыка"), ("el cine", "cinema", "кино"),
        ("bailar", "to dance", "танцевать"), ("cantar", "to sing", "петь"), ("nadar", "to swim", "плавать"),
        ("el fútbol", "soccer", "футбол"), ("jugar", "to play", "играть"), ("ganar", "to win", "выигрывать"),
        ("perder", "to lose", "проигрывать"), ("el equipo", "team", "команда"), ("entrenar", "to train", "тренироваться"),
        ("saber", "to know how", "уметь"), ("sé", "I know how", "я умею"), ("poder", "to be able", "мочь"),
        ("puedo", "I can", "я могу"), ("la guitarra", "guitar", "гитара"), ("tocar", "to play (instr.)", "играть (инстр.)"),
        ("leer", "to read", "читать"), ("dibujar", "to draw", "рисовать"), ("el pasatiempo", "hobby", "хобби"),
        ("divertirse", "to have fun", "веселиться")]),

    WK(23, "A2", "📱", "Technology & Communication", "Технологии и связь", "Tecnología y comunicación",
       theory(
           "Use phones and the internet, and give simple commands (imperatives).",
           "Пользуемся телефоном и интернетом, простые команды (императив).",
           "Usa el teléfono e internet, y da órdenes simples (imperativo).",
           "Informal commands: -ar → habla, -er/-ir → come/escribe. 'Mándame un mensaje' = send me a message.",
           "Команды (ты): -ar → habla, -er/-ir → come/escribe. «Mándame un mensaje» — напиши мне.",
           "Imperativo tú: habla, come, escribe. 'Mándame un mensaje'.",
           [("Mándame un mensaje.", "Send me a message.", "Напиши мне сообщение."),
            ("Llámame mañana.", "Call me tomorrow.", "Позвони мне завтра."),
            ("Descarga la aplicación.", "Download the app.", "Скачай приложение.")],
           "'el celular' = cell phone; 'la compu' = casual for computer.",
           "«el celular» — мобильный; «la compu» — разг. компьютер.",
           "'el celular' y 'la compu' (computadora)."),
       [("el celular", "cell phone (Mex.)", "мобильный"), ("la computadora", "computer (Mex.)", "компьютер"),
        ("el correo", "email", "почта"), ("la contraseña", "password", "пароль"), ("descargar", "to download", "скачивать"),
        ("enviar", "to send", "отправлять"), ("el mensaje", "message", "сообщение"), ("llamar", "to call", "звонить"),
        ("contestar", "to answer", "отвечать"), ("la aplicación", "app", "приложение"), ("la pantalla", "screen", "экран"),
        ("la red", "network", "сеть"), ("el internet", "internet", "интернет"), ("la foto", "photo", "фото"),
        ("el video", "video", "видео"), ("buscar", "to search", "искать"), ("guardar", "to save", "сохранять"),
        ("borrar", "to delete", "удалять"), ("prender", "to turn on (Mex.)", "включать"),
        ("apagar", "to turn off", "выключать"), ("la batería", "battery", "батарея"), ("cargar", "to charge", "заряжать")]),

    WK(24, "A2", "🎉", "Plans & Invitations", "Планы и приглашения", "Planes e invitaciones",
       theory(
           "Invite friends, accept or decline, and arrange to meet.",
           "Приглашаем друзей, соглашаемся/отказываемся, договариваемся о встрече.",
           "Invita a amigos, acepta o rechaza, y queda de verte.",
           "'¿Quieres...?' / '¿Te gustaría...?' to invite. 'quedar de verse' = to arrange to meet.",
           "«¿Quieres...?» / «¿Te gustaría...?» — приглашение. «quedar de verse» — договориться о встрече.",
           "'¿Quieres...?' o '¿Te gustaría...?' para invitar. 'quedar de verse'.",
           [("¿Quieres ir al cine?", "Do you want to go to the movies?", "Хочешь в кино?"),
            ("Claro que sí, con gusto.", "Sure, gladly.", "Конечно, с удовольствием."),
            ("¿A qué hora quedamos?", "What time shall we meet?", "Во сколько встречаемся?")],
           "'¡Va!' or 'sale' means 'OK, deal!' in Mexican slang.",
           "«¡Va!» или «sale» — «ок, договорились!» в мекс. сленге.",
           "'¡Va!' o 'sale' = '¡de acuerdo!'."),
       [("¿quieres...?", "do you want...?", "хочешь...?"), ("¿te gustaría?", "would you like?", "ты бы хотел?"),
        ("vamos", "let's go", "пойдём"), ("la fiesta", "party", "вечеринка"), ("invitar", "to invite", "приглашать"),
        ("quedar", "to arrange to meet", "договориться"), ("¿a qué hora?", "at what time?", "во сколько?"),
        ("claro que sí", "of course", "конечно да"), ("con gusto", "gladly", "с удовольствием"),
        ("lo siento", "I'm sorry", "извини"), ("no puedo", "I can't", "я не могу"), ("tal vez", "maybe", "может быть"),
        ("otro día", "another day", "в другой день"), ("la cita", "date/appointment", "свидание/встреча"),
        ("temprano", "early", "рано"), ("tarde", "late", "поздно"), ("juntos", "together", "вместе"),
        ("el fin de semana", "weekend", "выходные"), ("ocupado", "busy", "занят"), ("libre", "free", "свободен"),
        ("¡sale!", "OK/deal! (Mex.)", "договорились!"), ("¡va!", "OK! (Mex.)", "давай!")]),

    WK(25, "A2", "🌦️", "Weather & Seasons", "Погода и сезоны", "Clima y estaciones",
       theory(
           "Describe the weather and seasons using 'hace' and 'está'.",
           "Описываем погоду и сезоны через «hace» и «está».",
           "Describe el clima con 'hace' y 'está'.",
           "'Hace + calor/frío/sol/viento'; 'está nublado/lloviendo'. Seasons take 'en': en verano.",
           "«Hace + calor/frío/sol/viento»; «está nublado/lloviendo». Сезоны с «en»: en verano.",
           "'Hace calor/frío/sol'; 'está nublado'. Estaciones con 'en': en verano.",
           [("Hace mucho calor hoy.", "It's very hot today.", "Сегодня очень жарко."),
            ("Está lloviendo.", "It's raining.", "Идёт дождь."),
            ("En invierno hace frío.", "In winter it's cold.", "Зимой холодно.")],
           "Central Mexico has a rainy season ('temporada de lluvias') in summer.",
           "В центральной Мексике летом сезон дождей («temporada de lluvias»).",
           "El centro de México tiene temporada de lluvias en verano."),
       [("hace calor", "it's hot", "жарко"), ("hace frío", "it's cold", "холодно"), ("hace sol", "it's sunny", "солнечно"),
        ("hace viento", "it's windy", "ветрено"), ("está nublado", "it's cloudy", "облачно"), ("llueve", "it rains", "идёт дождь"),
        ("la lluvia", "rain", "дождь"), ("el clima", "weather", "погода"), ("la primavera", "spring", "весна"),
        ("el verano", "summer", "лето"), ("el otoño", "autumn", "осень"), ("el invierno", "winter", "зима"),
        ("el sol", "sun", "солнце"), ("la nube", "cloud", "облако"), ("el cielo", "sky", "небо"),
        ("la nieve", "snow", "снег"), ("caluroso", "hot (weather)", "жаркий"), ("fresco", "cool", "прохладный"),
        ("húmedo", "humid", "влажный"), ("seco", "dry", "сухой"), ("la temperatura", "temperature", "температура"),
        ("el grado", "degree", "градус")]),

    WK(26, "A2", "🏙️", "The City & Directions", "Город и направления", "La ciudad y direcciones",
       theory(
           "Ask for and give directions around town.",
           "Спрашиваем и даём направления по городу.",
           "Pide y da direcciones por la ciudad.",
           "Commands for directions: 'siga derecho', 'dé vuelta a la derecha'. 'está a dos cuadras'.",
           "Команды: «siga derecho», «dé vuelta a la derecha». «está a dos cuadras».",
           "'siga derecho', 'dé vuelta a la derecha', 'a dos cuadras'.",
           [("Siga derecho dos cuadras.", "Go straight two blocks.", "Идите прямо два квартала."),
            ("Dé vuelta a la izquierda.", "Turn left.", "Поверните налево."),
            ("Está junto al banco.", "It's next to the bank.", "Это рядом с банком.")],
           "Ask locals politely: 'Disculpe, ¿dónde está...?'.",
           "Вежливо спрашивайте местных: «Disculpe, ¿dónde está...?».",
           "'Disculpe, ¿dónde está...?' para preguntar."),
       [("la calle", "street", "улица"), ("la avenida", "avenue", "проспект"), ("la cuadra", "block", "квартал"),
        ("la esquina", "corner", "угол"), ("el semáforo", "traffic light", "светофор"), ("derecho", "straight", "прямо"),
        ("a la derecha", "to the right", "направо"), ("a la izquierda", "to the left", "налево"),
        ("junto a", "next to", "рядом с"), ("enfrente de", "in front of", "напротив"), ("detrás de", "behind", "позади"),
        ("cerca", "near", "близко"), ("lejos", "far", "далеко"), ("el edificio", "building", "здание"),
        ("la plaza", "square", "площадь"), ("el parque", "park", "парк"), ("la iglesia", "church", "церковь"),
        ("el museo", "museum", "музей"), ("disculpe", "excuse me (formal)", "извините"), ("seguir", "to continue", "продолжать"),
        ("dar vuelta", "to turn", "поворачивать"), ("cruzar", "to cross", "переходить")]),

    # ==================== B1 (weeks 27-38, ~months 7-9+) ====================
    WK(27, "B1", "💭", "Giving Opinions", "Выражение мнения", "Dar opiniones",
       theory(
           "Express and defend opinions, agree and disagree with nuance.",
           "Выражаем и отстаиваем мнение, соглашаемся и спорим с нюансами.",
           "Expresa y defiende opiniones, con matices.",
           "'Creo que + indicative'; 'No creo que + subjunctive'. Connect ideas: sin embargo, además, por eso.",
           "«Creo que + изъявит.»; «No creo que + сослагат.». Связки: sin embargo, además, por eso.",
           "'Creo que + indicativo'; 'No creo que + subjuntivo'. Conectores: sin embargo, además.",
           [("Creo que tienes razón.", "I think you're right.", "Думаю, ты прав."),
            ("No estoy de acuerdo.", "I don't agree.", "Я не согласен."),
            ("Es cierto, sin embargo...", "It's true, however...", "Верно, однако...")],
           "'la neta' = 'the truth/honestly' — a very Mexican way to be frank.",
           "«la neta» — «по правде/честно» — очень по-мексикански.",
           "'la neta' = la verdad, honestamente (muy mexicano)."),
       [("creo que", "I think that", "я думаю, что"), ("en mi opinión", "in my opinion", "по-моему"),
        ("estoy de acuerdo", "I agree", "я согласен"), ("no estoy de acuerdo", "I disagree", "я не согласен"),
        ("me parece", "it seems to me", "мне кажется"), ("depende", "it depends", "зависит"),
        ("además", "besides", "кроме того"), ("sin embargo", "however", "однако"), ("por eso", "that's why", "поэтому"),
        ("aunque", "although", "хотя"), ("es cierto", "it's true", "это правда"), ("es falso", "it's false", "это ложь"),
        ("tener razón", "to be right", "быть правым"), ("equivocarse", "to be wrong", "ошибаться"),
        ("la neta", "the truth (Mex.)", "правда/честно"), ("opinar", "to give an opinion", "высказывать мнение"),
        ("dudar", "to doubt", "сомневаться"), ("estar seguro", "to be sure", "быть уверенным"),
        ("quizás", "perhaps", "возможно"), ("obviamente", "obviously", "очевидно"),
        ("por un lado", "on one hand", "с одной стороны"), ("por otro lado", "on the other", "с другой стороны")]),

    WK(28, "B1", "🔮", "Future & Goals", "Будущее и цели", "Futuro y metas",
       theory(
           "Talk about the future with the future tense and describe your goals.",
           "Говорим о будущем (будущее время) и описываем цели.",
           "Habla del futuro con el tiempo futuro y describe tus metas.",
           "Future: infinitive + é/ás/á/emos/án (hablaré). Irregular stems: tendré, haré, seré, podré.",
           "Будущее: инфинитив + é/ás/á/emos/án (hablaré). Неправильные основы: tendré, haré, seré, podré.",
           "Futuro: infinitivo + é/ás/á (hablaré). Irregulares: tendré, haré, seré.",
           [("El próximo año viajaré.", "Next year I will travel.", "В следующем году я поеду путешествовать."),
            ("Seré doctor.", "I will be a doctor.", "Я стану врачом."),
            ("Lograré mi meta.", "I will achieve my goal.", "Я достигну своей цели.")],
           "Spanish also uses 'ir a + infinitive' for near future in daily speech.",
           "В разговоре часто «ir a + инфинитив» для ближайшего будущего.",
           "En el habla se usa 'ir a + infinitivo' para el futuro cercano."),
       [("viajaré", "I will travel", "я буду путешествовать"), ("haré", "I will do", "я сделаю"),
        ("seré", "I will be", "я буду"), ("tendré", "I will have", "у меня будет"),
        ("podré", "I will be able", "я смогу"), ("iré", "I will go", "я пойду"),
        ("el próximo año", "next year", "в следующем году"), ("el futuro", "future", "будущее"),
        ("la meta", "goal", "цель"), ("el sueño", "dream", "мечта"), ("lograr", "to achieve", "достигать"),
        ("esperar", "to hope/wait", "надеяться"), ("mejorar", "to improve", "улучшать"), ("cambiar", "to change", "менять"),
        ("planear", "to plan", "планировать"), ("el plan", "plan", "план"), ("pronto", "soon", "скоро"),
        ("algún día", "someday", "когда-нибудь"), ("el objetivo", "objective", "цель"),
        ("conseguir", "to get/obtain", "добиваться"), ("intentar", "to try", "пытаться"), ("prometer", "to promise", "обещать")]),

    WK(29, "B1", "📖", "Telling Stories (imperfect)", "Рассказы (имперфект)", "Contar historias (imperfecto)",
       theory(
           "Describe the past: what things were like and what you 'used to' do (imperfect).",
           "Описываем прошлое: как было и что «раньше делал» (имперфект).",
           "Describe el pasado: cómo eran las cosas y qué solías hacer (imperfecto).",
           "Imperfect: -ar → -aba; -er/-ir → -ía. Irregulars: era, iba, veía. Use it for descriptions & habits in the past.",
           "Имперфект: -ar → -aba; -er/-ir → -ía. Неправильные: era, iba, veía. Для описаний и привычек в прошлом.",
           "Imperfecto: -aba / -ía. Irregulares: era, iba, veía. Para descripciones y hábitos.",
           [("De niño jugaba mucho.", "As a child I used to play a lot.", "В детстве я много играл."),
            ("Era una casa grande.", "It was a big house.", "Это был большой дом."),
            ("Siempre íbamos al mar.", "We always went to the sea.", "Мы всегда ездили к морю.")],
           "Preterite = specific finished event; imperfect = background/habit. They work together.",
           "Претерит — конкретное событие; имперфект — фон/привычка. Работают вместе.",
           "Pretérito = evento puntual; imperfecto = fondo/hábito."),
       [("era", "I/he was", "был"), ("tenía", "I/he had", "имел"), ("hacía", "I/he did", "делал"),
        ("iba", "I/he went", "ходил"), ("vivía", "I/he lived", "жил"), ("veía", "I/he saw", "видел"),
        ("jugaba", "I used to play", "я играл"), ("de niño", "as a child", "в детстве"),
        ("antes", "before/back then", "раньше"), ("siempre", "always", "всегда"), ("mientras", "while", "пока"),
        ("cada día", "each day", "каждый день"), ("entonces", "back then/so", "тогда"),
        ("de repente", "suddenly", "вдруг"), ("primero", "first", "сначала"), ("finalmente", "finally", "наконец"),
        ("el recuerdo", "memory", "воспоминание"), ("recordar", "to remember", "помнить"),
        ("la historia", "story/history", "история"), ("el pasado", "the past", "прошлое"),
        ("la infancia", "childhood", "детство"), ("solía", "I used to", "я обычно (раньше)")]),

    WK(30, "B1", "💼", "Work & Career", "Работа и карьера", "Trabajo y carrera",
       theory(
           "Discuss jobs, workplaces and job interviews with professional vocabulary.",
           "Обсуждаем работу, места и собеседования профессиональной лексикой.",
           "Habla de trabajos, oficinas y entrevistas con vocabulario profesional.",
           "Use 'llevar + time + gerund': 'llevo tres años trabajando aquí' = I've been working here 3 years.",
           "«llevar + время + герундий»: «llevo tres años trabajando aquí» — работаю здесь 3 года.",
           "'llevar + tiempo + gerundio': 'llevo tres años trabajando aquí'.",
           [("Trabajo en una empresa grande.", "I work at a big company.", "Я работаю в большой компании."),
            ("Tengo una entrevista mañana.", "I have an interview tomorrow.", "Завтра у меня собеседование."),
            ("Llevo dos años en este puesto.", "I've been in this position 2 years.", "Я на этой должности 2 года.")],
           "'chamba' is Mexican slang for 'work/job'; 'chambear' = to work.",
           "«chamba» — мекс. сленг «работа»; «chambear» — работать.",
           "'chamba' = trabajo (mexicanismo); 'chambear' = trabajar."),
       [("la empresa", "company", "компания"), ("el jefe", "boss", "начальник"), ("la reunión", "meeting", "встреча"),
        ("el sueldo", "salary", "зарплата"), ("el horario", "schedule", "график"), ("la entrevista", "interview", "собеседование"),
        ("contratar", "to hire", "нанимать"), ("renunciar", "to quit", "увольняться"), ("el ascenso", "promotion", "повышение"),
        ("la experiencia", "experience", "опыт"), ("el proyecto", "project", "проект"), ("la oportunidad", "opportunity", "возможность"),
        ("el puesto", "position", "должность"), ("la oficina", "office", "офис"), ("el cliente", "client", "клиент"),
        ("el compañero", "coworker", "коллега"), ("la chamba", "work (Mex.)", "работа"), ("chambear", "to work (Mex.)", "работать"),
        ("el currículum", "résumé", "резюме"), ("la carrera", "career/degree", "карьера"),
        ("ganar", "to earn", "зарабатывать"), ("el negocio", "business", "бизнес")]),

    WK(31, "B1", "🌍", "Society & Environment", "Общество и экология", "Sociedad y medio ambiente",
       theory(
           "Discuss the environment and social issues; use impersonal 'se'.",
           "Обсуждаем экологию и общество; безличное «se».",
           "Habla del medio ambiente y temas sociales; usa el 'se' impersonal.",
           "Impersonal 'se': 'se debe reciclar' = one should recycle; 'se dice que...' = it's said that...",
           "Безличное «se»: «se debe reciclar» — нужно перерабатывать; «se dice que...» — говорят, что...",
           "'se' impersonal: 'se debe reciclar'; 'se dice que...'.",
           [("Se debe cuidar la naturaleza.", "One must care for nature.", "Нужно беречь природу."),
            ("Hay mucha contaminación.", "There's a lot of pollution.", "Много загрязнения."),
            ("Se dice que va a cambiar.", "It's said it will change.", "Говорят, что изменится.")],
           "Mexico City has worked for years to reduce its famous smog.",
           "Мехико годами борется со своим знаменитым смогом.",
           "La CDMX lleva años reduciendo su famoso esmog."),
       [("el medio ambiente", "environment", "окружающая среда"), ("la basura", "trash", "мусор"),
        ("reciclar", "to recycle", "перерабатывать"), ("contaminar", "to pollute", "загрязнять"),
        ("la contaminación", "pollution", "загрязнение"), ("la naturaleza", "nature", "природа"),
        ("cuidar", "to take care of", "беречь"), ("el planeta", "planet", "планета"), ("el agua", "water", "вода"),
        ("la energía", "energy", "энергия"), ("el árbol", "tree", "дерево"), ("el bosque", "forest", "лес"),
        ("la sociedad", "society", "общество"), ("el gobierno", "government", "правительство"),
        ("la pobreza", "poverty", "бедность"), ("la educación", "education", "образование"),
        ("el problema", "problem", "проблема"), ("la solución", "solution", "решение"),
        ("proteger", "to protect", "защищать"), ("ahorrar", "to save (resources)", "экономить"),
        ("el cambio", "change", "изменение"), ("mejorar", "to improve", "улучшать")]),

    WK(32, "B1", "💀", "Mexican Culture", "Мексиканская культура", "Cultura mexicana",
       theory(
           "Dive into Mexican traditions like Día de Muertos, food and festivals.",
           "Погружаемся в мексиканские традиции: Día de Muertos, еда, праздники.",
           "Conoce tradiciones mexicanas: Día de Muertos, comida y fiestas.",
           "Cultural note over grammar this week: learn vocabulary tied to real celebrations and describe them in the past & present.",
           "На этой неделе — культура: лексика реальных праздников; описывайте их в прошедшем и настоящем.",
           "Esta semana, cultura: vocabulario de fiestas reales; descríbelas en pasado y presente.",
           [("El Día de Muertos es en noviembre.", "Day of the Dead is in November.", "День мёртвых в ноябре."),
            ("Ponemos una ofrenda.", "We set up an offering.", "Мы ставим подношение."),
            ("El mariachi toca en la fiesta.", "The mariachi plays at the party.", "Мариачи играют на празднике.")],
           "Día de Muertos (Nov 1-2) celebrates loved ones with altars, marigolds and pan de muerto.",
           "Día de Muertos (1-2 ноября) чтит близких: алтари, бархатцы и pan de muerto.",
           "El Día de Muertos honra a los seres queridos con altares y cempasúchil."),
       [("la tradición", "tradition", "традиция"), ("la fiesta", "celebration", "праздник"), ("el altar", "altar", "алтарь"),
        ("la calavera", "skull", "череп"), ("la ofrenda", "offering", "подношение"), ("celebrar", "to celebrate", "праздновать"),
        ("el mole", "mole (dish)", "моле"), ("el pan de muerto", "day-of-dead bread", "хлеб мёртвых"),
        ("el mariachi", "mariachi", "мариачи"), ("la piñata", "piñata", "пиньята"), ("el desfile", "parade", "парад"),
        ("los fuegos artificiales", "fireworks", "фейерверк"), ("la cultura", "culture", "культура"),
        ("la costumbre", "custom", "обычай"), ("el pueblo", "town/people", "посёлок/народ"),
        ("la música", "music", "музыка"), ("el baile", "dance", "танец"), ("la vela", "candle", "свеча"),
        ("la flor", "flower", "цветок"), ("el difunto", "the deceased", "усопший"),
        ("recordar", "to remember", "помнить"), ("el orgullo", "pride", "гордость")]),

    WK(33, "B1", "🤔", "Wishes & the Conditional", "Желания и условное", "Deseos y condicional",
       theory(
           "Be polite and hypothetical with the conditional ('would') and simple 'if' sentences.",
           "Вежливость и гипотезы: условное наклонение («бы») и простые «если».",
           "Sé cortés e hipotético con el condicional y frases con 'si'.",
           "Conditional: infinitive + ía (hablaría = I would speak). 'Si tuviera dinero, viajaría' (if I had money, I'd travel).",
           "Условное: инфинитив + ía (hablaría = я бы говорил). «Si tuviera dinero, viajaría».",
           "Condicional: infinitivo + ía. 'Si tuviera dinero, viajaría'.",
           [("Me gustaría viajar.", "I would like to travel.", "Мне бы хотелось путешествовать."),
            ("Yo, en tu lugar, iría.", "In your place, I would go.", "На твоём месте я бы пошёл."),
            ("¿Podría ayudarme?", "Could you help me?", "Вы могли бы помочь?")],
           "Use the conditional to sound polite: 'podría', 'me gustaría', 'sería'.",
           "Условное звучит вежливо: «podría», «me gustaría», «sería».",
           "El condicional suena cortés: 'podría', 'me gustaría'."),
       [("me gustaría", "I would like", "мне бы хотелось"), ("sería", "it would be", "было бы"),
        ("haría", "I would do", "я бы сделал"), ("podría", "I/you could", "мог бы"),
        ("tendría", "I would have", "у меня было бы"), ("iría", "I would go", "я бы пошёл"),
        ("si tuviera", "if I had", "если бы у меня было"), ("si pudiera", "if I could", "если бы я мог"),
        ("en tu lugar", "in your place", "на твоём месте"), ("ojalá", "hopefully/I wish", "хоть бы"),
        ("el deseo", "wish", "желание"), ("desear", "to wish", "желать"), ("preferir", "to prefer", "предпочитать"),
        ("prefiero", "I prefer", "я предпочитаю"), ("imaginar", "to imagine", "представлять"),
        ("suponer", "to suppose", "предполагать"), ("quizás", "maybe", "возможно"),
        ("probablemente", "probably", "вероятно"), ("de todos modos", "anyway", "в любом случае"),
        ("por si acaso", "just in case", "на всякий случай"), ("con tal de", "as long as", "лишь бы"),
        ("a menos que", "unless", "если только не")]),

    WK(34, "B1", "❤️", "Relationships & Emotions", "Отношения и эмоции", "Relaciones y emociones",
       theory(
           "Talk about feelings and relationships in depth.",
           "Глубоко говорим о чувствах и отношениях.",
           "Habla de sentimientos y relaciones a fondo.",
           "Verbs of emotion often use reflexive/indirect forms: me alegro de, me preocupa que, me molesta que (+ subjunctive).",
           "Глаголы эмоций часто возвратные/косвенные: me alegro de, me preocupa que, me molesta que (+ сослагат.).",
           "Verbos de emoción: me alegro de, me preocupa que (+ subjuntivo).",
           [("Me alegro de verte.", "I'm glad to see you.", "Рад тебя видеть."),
            ("Me preocupa que no venga.", "I'm worried he won't come.", "Меня беспокоит, что он не придёт."),
            ("Nos llevamos muy bien.", "We get along very well.", "Мы отлично ладим.")],
           "'llevarse bien/mal con alguien' = to get along well/badly with someone.",
           "«llevarse bien/mal с кем-то» — ладить/не ладить.",
           "'llevarse bien/mal con alguien'."),
       [("emocionado", "excited", "взволнованный"), ("preocupado", "worried", "обеспокоенный"),
        ("orgulloso", "proud", "гордый"), ("celoso", "jealous", "ревнивый"), ("agradecido", "grateful", "благодарный"),
        ("sorprendido", "surprised", "удивлённый"), ("la amistad", "friendship", "дружба"),
        ("confiar", "to trust", "доверять"), ("discutir", "to argue", "спорить"), ("perdonar", "to forgive", "прощать"),
        ("extrañar", "to miss (someone)", "скучать"), ("apoyar", "to support", "поддерживать"),
        ("el amor", "love", "любовь"), ("querer", "to love/want", "любить/хотеть"), ("odiar", "to hate", "ненавидеть"),
        ("alegrarse", "to be glad", "радоваться"), ("enojarse", "to get angry", "злиться"),
        ("llevarse bien", "to get along", "ладить"), ("el sentimiento", "feeling", "чувство"),
        ("la pareja", "couple/partner", "пара"), ("enamorarse", "to fall in love", "влюбляться"),
        ("la confianza", "trust", "доверие")]),

    WK(35, "B1", "📰", "News & Media", "Новости и СМИ", "Noticias y medios",
       theory(
           "Understand and discuss the news and report what others say.",
           "Понимаем и обсуждаем новости, пересказываем чужие слова.",
           "Entiende y comenta noticias; reporta lo que dicen otros.",
           "Reported speech: 'Dijo que iba a llover' (He said it was going to rain). Present → imperfect when reporting past.",
           "Косвенная речь: «Dijo que iba a llover». Настоящее → имперфект при пересказе прошлого.",
           "Estilo indirecto: 'Dijo que iba a llover'.",
           [("Según las noticias, hará frío.", "According to the news, it'll be cold.", "По новостям, будет холодно."),
            ("El periódico dice que...", "The newspaper says that...", "Газета пишет, что..."),
            ("Dijo que vendría.", "He said he would come.", "Он сказал, что придёт.")],
           "Question everything: 'según' = according to; useful for citing sources.",
           "«según» — согласно/по (источнику); полезно для ссылок.",
           "'según' = de acuerdo con (para citar fuentes)."),
       [("las noticias", "the news", "новости"), ("el periódico", "newspaper", "газета"),
        ("el gobierno", "government", "правительство"), ("la economía", "economy", "экономика"),
        ("suceder", "to happen", "происходить"), ("informar", "to inform", "информировать"),
        ("según", "according to", "согласно"), ("el reportaje", "report", "репортаж"), ("la entrevista", "interview", "интервью"),
        ("el canal", "channel", "канал"), ("la prensa", "press", "пресса"), ("el titular", "headline", "заголовок"),
        ("anunciar", "to announce", "объявлять"), ("aumentar", "to increase", "увеличивать"),
        ("disminuir", "to decrease", "уменьшать"), ("el suceso", "event", "событие"),
        ("mundial", "global", "мировой"), ("nacional", "national", "национальный"),
        ("local", "local", "местный"), ("el testigo", "witness", "свидетель"),
        ("la fuente", "source", "источник"), ("verdadero", "true", "правдивый")]),

    WK(36, "B1", "🔗", "Connectors & Fluency", "Связки и беглость", "Conectores y fluidez",
       theory(
           "Sound fluent by linking your ideas smoothly with advanced connectors.",
           "Звучим бегло: плавно связываем мысли продвинутыми коннекторами.",
           "Suena fluido enlazando ideas con conectores avanzados.",
           "Structure a talk: 'por un lado... por otro lado', 'en primer lugar', 'en resumen', 'a pesar de'.",
           "Стройте речь: «por un lado... por otro lado», «en primer lugar», «en resumen», «a pesar de».",
           "Estructura: 'por un lado... por otro', 'en resumen', 'a pesar de'.",
           [("Por lo tanto, decidí quedarme.", "Therefore, I decided to stay.", "Поэтому я решил остаться."),
            ("A pesar de la lluvia, salimos.", "Despite the rain, we went out.", "Несмотря на дождь, мы вышли."),
            ("En resumen, fue un buen día.", "In short, it was a good day.", "В итоге, день был хорош.")],
           "Connectors are the secret to sounding advanced with simple vocabulary.",
           "Коннекторы — секрет «продвинутой» речи при простой лексике.",
           "Los conectores te hacen sonar avanzado con vocabulario simple."),
       [("por lo tanto", "therefore", "следовательно"), ("a pesar de", "despite", "несмотря на"),
        ("en cambio", "on the other hand", "напротив"), ("por ejemplo", "for example", "например"),
        ("es decir", "that is to say", "то есть"), ("en resumen", "in summary", "в итоге"),
        ("en primer lugar", "firstly", "во-первых"), ("por cierto", "by the way", "кстати"),
        ("de hecho", "in fact", "фактически"), ("mientras tanto", "meanwhile", "тем временем"),
        ("sin duda", "no doubt", "без сомнения"), ("al contrario", "on the contrary", "наоборот"),
        ("así que", "so", "так что"), ("ya que", "since/because", "так как"), ("además", "furthermore", "к тому же"),
        ("finalmente", "finally", "наконец"), ("por otra parte", "on the other hand", "с другой стороны"),
        ("en conclusión", "in conclusion", "в заключение"), ("tanto... como", "both... and", "как... так и"),
        ("no obstante", "nevertheless", "тем не менее"), ("gracias a", "thanks to", "благодаря"),
        ("debido a", "due to", "из-за")]),

    WK(37, "B1", "🧠", "Subjunctive Basics", "Основы сослагательного", "El subjuntivo básico",
       theory(
           "Meet the subjunctive — used for wishes, doubts and emotions. A big B1 milestone!",
           "Знакомимся с сослагательным — желания, сомнения, эмоции. Важная веха B1!",
           "Conoce el subjuntivo — deseos, dudas y emociones. ¡Un gran paso en B1!",
           "Present subjunctive flips the vowel: hablar → hable; comer → coma. Triggers: 'espero que', 'quiero que', 'ojalá que'.",
           "Настоящее сослагательное меняет гласную: hablar → hable; comer → coma. Триггеры: «espero que», «quiero que», «ojalá que».",
           "Subjuntivo: hablar → hable; comer → coma. Disparadores: 'espero que', 'quiero que', 'ojalá'.",
           [("Espero que estés bien.", "I hope you're well.", "Надеюсь, ты в порядке."),
            ("Quiero que vengas.", "I want you to come.", "Я хочу, чтобы ты пришёл."),
            ("Ojalá que llueva.", "I hope it rains.", "Хоть бы пошёл дождь.")],
           "If there are two different subjects + a wish/doubt, you'll likely need the subjunctive.",
           "Два разных подлежащих + желание/сомнение — скорее всего нужен субхунтив.",
           "Dos sujetos distintos + deseo/duda → subjuntivo."),
       [("espero que", "I hope that", "надеюсь, что"), ("quiero que", "I want that", "хочу, чтобы"),
        ("ojalá", "hopefully", "хоть бы"), ("es importante que", "it's important that", "важно, чтобы"),
        ("dudo que", "I doubt that", "сомневаюсь, что"), ("hable", "(that) I/he speak", "чтобы говорил"),
        ("coma", "(that) I/he eat", "чтобы ел"), ("viva", "(that) I/he live", "чтобы жил"),
        ("sea", "(that) it be", "чтобы был"), ("tenga", "(that) I/he have", "чтобы имел"),
        ("venga", "(that) I/he come", "чтобы пришёл"), ("haga", "(that) I/he do", "чтобы делал"),
        ("vaya", "(that) I/he go", "чтобы шёл"), ("pueda", "(that) I/he can", "чтобы мог"),
        ("necesitar", "to need", "нуждаться"), ("pedir", "to ask for", "просить"),
        ("recomendar", "to recommend", "рекомендовать"), ("aconsejar", "to advise", "советовать"),
        ("temer", "to fear", "бояться"), ("alegrarse de", "to be glad about", "радоваться"),
        ("antes de que", "before", "прежде чем"), ("para que", "so that", "чтобы")]),

    WK(38, "B1", "🎓", "B1 Consolidation", "Закрепление B1", "Consolidación B1",
       theory(
           "You've reached solid B1! This week weaves together past, future, opinions and the subjunctive.",
           "Вы достигли уверенного B1! Эта неделя связывает прошлое, будущее, мнения и субхунтив.",
           "¡Llegaste a un B1 sólido! Esta semana integra pasado, futuro, opiniones y subjuntivo.",
           "Practice switching tenses naturally and expressing nuanced ideas. You can now hold real conversations.",
           "Тренируйте естественное переключение времён и выражение нюансов. Вы уже можете вести реальные беседы.",
           "Practica cambiar de tiempos y expresar matices. Ya puedes conversar de verdad.",
           [("Cuando era niño, quería ser piloto.", "When I was a kid, I wanted to be a pilot.", "В детстве я хотел стать пилотом."),
            ("Espero que el próximo año sea mejor.", "I hope next year is better.", "Надеюсь, следующий год будет лучше."),
            ("Aunque llueva, iremos.", "Even if it rains, we'll go.", "Даже если пойдёт дождь, мы пойдём.")],
           "¡Felicidades! Keep practicing daily — fluency is built one conversation at a time.",
           "¡Felicidades! Практикуйтесь ежедневно — беглость строится по одной беседе.",
           "¡Felicidades! Practica a diario; la fluidez se construye conversando."),
       [("la conversación", "conversation", "беседа"), ("el idioma", "language", "язык"),
        ("aprender", "to learn", "учить"), ("practicar", "to practice", "практиковать"),
        ("mejorar", "to improve", "улучшать"), ("el nivel", "level", "уровень"),
        ("con fluidez", "fluently", "бегло"), ("el reto", "challenge", "вызов"),
        ("lograr", "to achieve", "достигать"), ("orgulloso", "proud", "гордый"),
        ("seguir", "to keep on", "продолжать"), ("adelante", "onward", "вперёд"),
        ("el esfuerzo", "effort", "усилие"), ("valer la pena", "to be worth it", "стоить того"),
        ("poco a poco", "little by little", "постепенно"), ("cada vez mejor", "better each time", "всё лучше"),
        ("dominar", "to master", "овладеть"), ("el logro", "achievement", "достижение"),
        ("celebrar", "to celebrate", "праздновать"), ("continuar", "to continue", "продолжать")]),
]
